### ISSUE TITLE
使用exception追踪报错信息时，超过127个字节会自动截断

### ISSUE THREAD

**Issue by b-ing** [Delgan/loguru#1007]
当传入的内容超过到127时，会自动截断后三位为...，如何取消这种截断

`2023-10-12 12:30:56.865 | ERROR    | __main__:<module>:25 - fadsa
Traceback (most recent call last):

> File "E:\yugu_project\test\test_log.py", line 22, in <module>
    test(2, 0)
    └ <function test at 0x000001114FF52EE0>

  File "E:\yugu_project\test\test_log.py", line 17, in test
    res = a + c / b
          │   │   └ 0
          │   └ 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa12345...
          └ 2

TypeError: unsupported operand type(s) for /: 'str' and 'int'`

**Comment by Delgan** [comment]
Due to its length, the message is intentionally truncated to prevent it from polluting the traceback output.

You can implement your own exeception formatter if you need to change this behavior: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).
