### ISSUE TITLE
logger.catch ignore _pytest and pluggy info for pytest 

### ISSUE THREAD

**Issue by m3lab-zzl** [Delgan/loguru#1020]
I added logger.catch decorator to some functions so that it can report values when something goes wrong. This works perfect for normal scripts, but for pytest, I always get many irrelevant traces from pluggy and _pytest modules:

```txt
Traceback (most recent call last):

  File "/home/zzl/miniconda3/envs/hk/bin/pytest", line 8, in <module>
    sys.exit(console_main())
    │   │    └ <function console_main at 0x7fbf5f580860>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/config/__init__.py", line 192, in console_main
    code = main()
           └ <function main at 0x7fbf5f580720>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/config/__init__.py", line 169, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
         │     │                │      │    └ <HookCaller 'pytest_cmdline_main'>
         │     │                │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7fbf5f3f2710>
         │     │                └ <_pytest.config.Config object at 0x7fbf5f3fcb90>
         │     └ <enum 'ExitCode'>
         └ typing.Union
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'config': <_pytest.config.Config object at 0x7fbf5f3fcb90>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_cmdline_main'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_cmdline_main'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_cmdline_main'>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7fbf5f3fcb90>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7fbf5f9bfce0>
           └ <_pytest.config.PytestPluginManager object at 0x7fbf5f310810>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7fbf5f3fcb90>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_...
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7fbf5f63f1a0>
           │            └ <_pytest.config.Config object at 0x7fbf5f3fcb90>
           └ <function wrap_session at 0x7fbf5f63f100>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/main.py", line 271, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
    │       │            │    └ <_pytest.config.Config object at 0x7fbf5f3fcb90>
    │       │            └ <function _main at 0x7fbf5f63f1a0>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/main.py", line 325, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>
    │      │    └ <HookCaller 'pytest_runtestloop'>
    │      └ <_pytest.config.compat.PathAwareHookProxy object at 0x7fbf5f3f2710>
    └ <_pytest.config.Config object at 0x7fbf5f3fcb90>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtestloop'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtestloop'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtestloop'>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7fbf5f9bfce0>
           └ <_pytest.config.PytestPluginManager object at 0x7fbf5f310810>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=0 testscollected=1>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_...
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/main.py", line 350, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │                                        │              └ None
    │    │                                        └ <Function test_PlotterBS>
    │    └ <member 'config' of 'Node' objects>
    └ <Function test_PlotterBS>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'item': <Function test_PlotterBS>, 'nextitem': None}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_protocol'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_protocol'>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_PlotterBS>, 'nextitem': None}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packa...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7fbf5f9bfce0>
           └ <_pytest.config.PytestPluginManager object at 0x7fbf5f310810>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_PlotterBS>, None]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packag...
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/runner.py", line 114, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
    │               │              └ None
    │               └ <Function test_PlotterBS>
    └ <function runtestprotocol at 0x7fbf5f63e2a0>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/runner.py", line 133, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ True
    │       │      │               └ <Function test_PlotterBS>
    │       │      └ <function call_and_report at 0x7fbf5f63e660>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_plot.py::Test_plot::test_PlotterBS' when='setup' outcome='passed'>]
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/runner.py", line 222, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_PlotterBS>
           └ <function call_runtest_hook at 0x7fbf5f63e840>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/runner.py", line 261, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7fbf5f63eac0>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7fbf5f2ef740>
            │        └ +TResult
            └ typing.Optional
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_PlotterBS>
            └ <HookCaller 'pytest_runtest_call'>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ False
           │    │         │    │     │    │           └ {'item': <Function test_PlotterBS>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_runtest_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_runtest_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_runtest_call'>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_PlotterBS>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packa...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7fbf5f9bfce0>
           └ <_pytest.config.PytestPluginManager object at 0x7fbf5f310810>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_PlotterBS>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packag...
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7fbf5f4914e0>
    └ <Function test_PlotterBS>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_PlotterBS>
    │    └ <property object at 0x7fbf5f591c10>
    └ <Function test_PlotterBS>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           │    │         │    │     │    │           │       └ True
           │    │         │    │     │    │           └ {'pyfuncitem': <Function test_PlotterBS>}
           │    │         │    │     │    └ <member '_hookimpls' of 'HookCaller' objects>
           │    │         │    │     └ <HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ <member 'name' of 'HookCaller' objects>
           │    │         └ <HookCaller 'pytest_pyfunc_call'>
           │    └ <member '_hookexec' of 'HookCaller' objects>
           └ <HookCaller 'pytest_pyfunc_call'>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_PlotterBS>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packa...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7fbf5f9bfce0>
           └ <_pytest.config.PytestPluginManager object at 0x7fbf5f310810>
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_PlotterBS>]
          │         └ <member 'function' of 'HookImpl' objects>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packag...
  File "/home/zzl/miniconda3/envs/hk/lib/python3.11/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {}
             └ <bound method Test_plot.test_PlotterBS of <test_plot.Test_plot object at 0x7fbf5f3394d0>>

  File "/home/zzl/Documents/demo/tests/test_plot.py", line 35, in test_PlotterBS
    bs = read_band("raw_data/band.h5")
         └ <function read_band at 0x7fbf16db54e0>
```
How to ignore them to keep the trace messages clean?

**Comment by Delgan** [comment]
Hi.

Loguru reproduces the complete traceback that would have been reported if the exception hadn't been captured. This provides you with all the relevant context. However, it can indeed be quite verbose, especially when third-party libraries are involved.

Do you need the logger when running unit tests with `pytest`? You could simply remove the sink you configured to avoid logs polluting the output of your tests. Alternatively, you could replace the sink and use `logger.add(sys.stderr, backtrace=False, diagnose=False)` to reduce the verbosity of logged tracebacks.

**Comment by m3lab-zzl** [comment]
@Delgan 

Hi, 

Thank you for your suggestion. I am not familiar with the `sink` concept. I tried adding `logger.add(sys.stderr, backtrace=False, diagnose=False)` to the test_*.py or modules, but nothing changed.

pytest only points out which line cause the error, but no values are attached, so I would like to keep loguru activated. 

I added catch functions only in my modules, not in the test_*.py. But there are still many `pytest` and `pluggy` stuff in the tracebacks.

I just want to filter out error messages from `pytest` and `pluggy` modules. The tracebacks should start with my module, such as `File "/home/zzl/Documents/demo/tests/test_plot.py"`

**Comment by Delgan** [comment]
A "sink" is simply where the messages are sent and logged.

The `logger` is configured with a default sink which logs to `stderr` for convenience. It can be quite verbose.

I would recommend the following approach:
- In the `conftest.py` of Pytest, create an auto-used `fixture` in charge of:
    - First calling `logger.remove()` to remove the default handler
    - Then calling `logger.add(sys.stderr, backtrace=False, diagnose=False)`
- Make sure you're not inadvertently calling `logger.add()` or `logger.remove()` in the code you're testing, otherwise it would cancel the above  configuration

However, if you're mainly interested in seeing values in errors reported by Pytest, I'd advise you to increase `pytest` verbosity or try to find an appropriate plugin. That would seem simpler than using Loguru in this case.

**Comment by m3lab-zzl** [comment]
Hi @Delgan , Thank you for your instruction, I created a `conftest.py` file in the test directory with the following contents:

```py
import pytest
from loguru import logger
import sys

@pytest.fixture(autouse=True)
def configure_logger():
    logger.remove()
    logger.add(sys.stderr, colorize=True, backtrace=False, diagnose=True)
```

Now pytest reports error just like run with normal scripts, which is what I need. Many thanks. 🎉
