### ISSUE TITLE
`@logger.catch(reraise=True)` only displays stack trace in one sink

### ISSUE THREAD

**Issue by jakobnissen** [Delgan/loguru#1021]
This may be a bug, or may just be me not understanding how `loguru` works.
The issue is that if you have multiple sinks added to the logger, only one of them will display the stack trace, in case the function that is being logged throws an exception.

This error seems to only occur under the following circumstances:
* There are multiple sinks
* A custom log formatter is used
* `@logger.catch(reraise=True)` is used.

Minimal working example:
```
from loguru import logger
import sys

def fmt(record):
    return "{message}"

logger.remove()
logger.add(sys.stderr, format=fmt)
logger.add("/tmp/foo.txt", format=fmt)

@logger.catch(reraise=True)
def err():
    raise ValueError()

err()
```
Now when I run it, I see the following correct output in `stderr`:
```
An error has been caught in function '<module>', process 'MainProcess' (58312), thread 'MainThread' (140069358892864):Traceback (most recent call last):
  File "/tmp/foo.py", line 15, in <module>
    err()
  File "/tmp/logger/lib/python3.11/site-packages/loguru/_logger.py", line 1277, in catch_wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/foo.py", line 13, in err
    raise ValueError()
ValueError
```
However, the log file `/tmp/foo.txt` only has this content, without the actual track trace being shown:
```
An error has been caught in function '<module>', process 'MainProcess' (58312), thread 'MainThread' (140069358892864):
```

**Comment by jakobnissen** [comment]
Ah, I didn't read the documentation carefully enough:
> However, note that in such a case, you should take care of appending the line ending and exception field to the returned format, while "\n{exception}" is automatically appended for convenience if format is a string.

Adding this indeed does solve the issue. Closing as solved.
