### ISSUE TITLE
A way to 'hide' low-level/packages from tracebacks

### ISSUE THREAD

**Issue by Zensonaton** [Delgan/loguru#1030]
When exception is raised, a lot of 'useless' data (like low-level/package method calls) is printed in the logs. Things are even worse when `backtrace=True` is used:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "test.py", line 13, in main
    while True:
KeyboardInterrupt
```

I wonder if there is a way to hide package/low-level calls from the traceback, while preserving code that is written by user. Something like this would be a lot better:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "test.py", line 13, in main
    while True:
KeyboardInterrupt
```

Sample code:
```python
import asyncio

from loguru import logger


async def main():
  logger.info("Press CTRL+C to raise KeyboardInterrupt exception")

  while True:
    pass

if __name__ == "__main__":
  asyncio.get_event_loop().run_until_complete(main())
```

**Comment by Delgan** [comment]
Loguru attempts to mimic the native formatting of exceptions. I don't think it would be good to deviate too much from the built-in way exceptions are formatted. The verbosity often provides additional context which can be very useful.

However, note that Loguru tries to emphasize frames from user code. Here is an example when `diagnose=True`:

```log
2023-11-28 21:51:31.907 | ERROR    | __main__:<module>:11 - An error has been caught in function '<module>', process 'MainProcess' (70523), thread 'MainThread' (140067035162432):
Traceback (most recent call last):

> File "/home/delgan/programming/loguru/test.py", line 13, in <module>
    asyncio.get_event_loop().run_until_complete(main())
    │       │                                   └ <function main at 0x7f63e51984a0>
    │       └ <built-in function get_event_loop>
    └ <module 'asyncio' from '/usr/lib/python3.11/asyncio/__init__.py'>

  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f63e4c685e0>
    └ <_UnixSelectorEventLoop running=False closed=False debug=False>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f63e4c6a3e0>
    └ <_UnixSelectorEventLoop running=False closed=False debug=False>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f63e4bbc900>
    └ <Handle <TaskStepMethWrapper object at 0x7f63e4487a60>()>
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f63e4487a60>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f63e4487a60>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f63e4487a60>()>

  File "/home/delgan/programming/loguru/test.py", line 5, in main
    async def main():
              └ <function main at 0x7f63e51984a0>

KeyboardInterrupt
```

Additionally, here is an example of colored output when `diagnose=False`:

![2023-11-28T21:49:01,787621143+01:00](https://github.com/Delgan/loguru/assets/4193924/be9f5f6e-d15f-4b4b-8ddb-25a8077b4806)

For alternative exception formatting, consider installing your own formatter: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).

**Comment by linpan** [comment]
sys.tracebacklimit = 2
