### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by CT-34589** [Delgan/loguru#1047]
fresh install of loguru, testing with exampls from the docs and returns an import error: ImportError: cannot import name 'logger' from partially initialized module 'loguru' (most likely due to a circular import)

`
from loguru import logger

logger.debug("Testing!")
`

Traceback (most recent call last):
  File "C:\Users\p\Desktop\104Systems\Bot\utils\logging.py", line 1, in <module>
    from loguru import logger
  File "C:\Users\p\Desktop\104Systems\.venv\Lib\site-packages\loguru\__init__.py", line 10, in <module>
    from ._logger import Core as _Core
  File "C:\Users\p\Desktop\104Systems\.venv\Lib\site-packages\loguru\_logger.py", line 88, in <module>
    import logging
  File "C:\Users\p\Desktop\104Systems\Bot\utils\logging.py", line 1, in <module>
    from loguru import logger
ImportError: cannot import name 'logger' from partially initialized module 'loguru' (most likely due to a circular import) (C:\Users\p\Desktop\104Systems\.venv\Lib\site-packages\loguru\__init__.py)

**Comment by Delgan** [comment]
Try renaming your `logging.py` file to something else to avoid name conflict with the built-in [`logging`](https://docs.python.org/3/library/logging.html) module.
