### ISSUE TITLE
Include traceback to JSON

### ISSUE THREAD

**Issue by sky-py** [Delgan/loguru#1217]
Is there any way to add loguru's beautiful traceback (like that when adding `backtrace=True, diagnose=True` to log) to CUSTOM JSON log?

For example for 
```python
from loguru import logger
import json


def json_formatter(record):
    log_object = {
        'timestamp': record['time'].strftime('%Y-%m-%d %H:%M:%S'),
        'level': record['level'].name,
        'message': record['message'],
        **record['extra']
    }

    return json.dumps(log_object, ensure_ascii=False)

def patching(record):
    record['extra']['serialized'] = json_formatter(record)

logger = logger.patch(patching)

logger.add('error.log',
           level='ERROR',
           format='{extra[serialized]}',
           )


@logger.catch
def error():
    order_id = '5555'
    data = {'email': 'invalid_email222', 'phone': 'invalid_phone222'}
    x = 10
    y = 0
    z = x / y

error()
```
getting:
```
{"timestamp": "2024-10-06 21:15:27", "level": "ERROR", "message": "An error has been caught in function '<module>', process 'MainProcess' (5572), thread 'MainThread' (7948):"}
Traceback (most recent call last):

> File "D:\User\Dropbox\Python\test\test3.py", line 34, in <module>
    error()
    └ <function error at 0x000001FF66294EA0>

  File "D:\User\Dropbox\Python\test\test3.py", line 32, in error
    z = x / y
        │   └ 0
        └ 10

ZeroDivisionError: division by zero
```

How to include
```
Traceback (most recent call last):

> File "D:\User\Dropbox\Python\test\test3.py", line 34, in <module>
    error()
    └ <function error at 0x000001FF66294EA0>

  File "D:\User\Dropbox\Python\test\test3.py", line 32, in error
    z = x / y
        │   └ 0
        └ 10

ZeroDivisionError: division by zero
```
to JSON?

**Comment by Delgan** [comment]
There is no built-in way, but you can use the [`better_exception`](https://github.com/Qix-/better-exceptions) library from which the Loguru tracebacks are derived.

**Comment by dmyersturnbull** [comment]
I find serialization unhelpful without tracebacks, so I took a similar approach to @sky-py. I checked out `better_exception` (thanks @Delgan) and ended up serializing the tracebacks (as `list[dict[...]]`).

While this works, the need for `patch` makes it awkward. It means I need a global `logger = loguru_logger.patch(...)` and to `from myapp.core import logger`. It's a little bit of unnecessary coupling.

It's not a big deal, just something I felt worth pointing out. I did add a way to limit the traceback depth (for serialized and non-serialized), per logging statement, which is actually pretty helpful.

**Comment by Delgan** [comment]
@dmyersturnbull Can you use the `patcher` attribute of the [`logger.configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) method maybe? 
That would patch the `logger` globally, avoiding the need for a custom `from myapp.core import logger` import.

**Comment by dmyersturnbull** [comment]
@Delgan Oops, I actually didn't know there was a `logger.configure` method, which your documentation covers nicely. `logger.configure` works perfectly.

I wanted to serialize the stack traces (up to a max depth), so I ended up writing my own serialization function.

By the way, [better-exceptions](https://github.com/Qix-/better-exceptions) appears at least somewhat unmaintained.
Loguru's  [`_better_exceptions.py`](https://github.com/Delgan/loguru/blob/master/loguru/_better_exceptions.py) (rationale in [commit `35239b`](https://github.com/Delgan/loguru/commit/35239b4081d6a16d008dc983915951d25c168343)) looks like a good alternative. The API looks [pretty stable](https://github.com/Delgan/loguru/compare/35239b..master#diff-ccb032e0ec345ddcc0a87baaacf7236552af45a80f1df3770215bb1d190776be), but I understand if you don't want to make it public.

**Comment by Delgan** [comment]
Yeah, I'm considering adding a new `logger.traceback()` method probably in the next release. :+1:

**Comment by ahulist** [comment]
> Yeah, I'm considering adding a new `logger.traceback()` method (in charge of formatting exception) probably in the next release. 👍

Has this happened yet by any chance?

**Comment by Delgan** [comment]
@ahulist No, sorry. This is something I still have in mind but this is not yet implemented.
