### ISSUE TITLE
Crash with forkserver as multiprocessing context

### ISSUE THREAD

**Issue by KaraKaraWitch** [Delgan/loguru#1264]
When attempting to use multiprocessing with forkserver context, loguru still spawns a simplequeue object which doesn't bode well. I've applied the recommendations in the readme but it doesn't seem to have any effect.

Stacktrace is as follows:

```
Traceback (most recent call last):
  File "/<Snip>/repro_simple.py", line 33, in <module>
    pool.apply_async(noop,args=(logger,)).get()
  File "/<Snip>/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/<Snip>/lib/python3.11/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/<Snip>/lib/python3.11/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<Snip>/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/<Snip>/lib/python3.11/multiprocessing/queues.py", line 356, in __getstate__
    context.assert_spawning(self)
  File "/<Snip>/lib/python3.11/multiprocessing/context.py", line 373, in assert_spawning
    raise RuntimeError(
RuntimeError: SimpleQueue objects should only be shared between processes through inheritance
```

The repro code:

```py
import multiprocessing as mp
import sys
from multiprocessing.reduction import ForkingPickler

if __name__ == "__main__":
    mp.set_start_method("forkserver")

    from loguru import logger

    mp_context = mp.get_context("forkserver")

    logger.remove()
    logger.configure(
        handlers=[
            {"sink": sys.stderr, "enqueue": True,"context":mp_context},
            {
                "sink": "{time}.log",
                "enqueue": True,
                "context": mp_context,
            },
        ]
    )

def noop(logger_instance):
    logger_instance.info("Noop!")

# Crashes...
# N.B. This happens when using multiprocessing pools with initalizers. 
# ForkingPickler.dumps(logger)

if __name__ == "__main__":
    with mp_context.Pool(processes=1) as pool:
        pool.apply_async(noop,args=(logger,)).get()
```

Extra Details:

- Python Version: 3.11.7
- loguru Version: 0.7.3
- OS: Ubuntu 22.04.5 LTS (Jammy) (Linux)
- Development Environment: VS Code via SSH (Shouldn't be relevant though.)

**Comment by KaraKaraWitch** [comment]
Just re-read the docs, I can't pass logger as an argument into the apply_async function. Let me see if I can rework around this...

**Comment by KaraKaraWitch** [comment]
```py
import multiprocessing as mp
import sys

if __name__ == "__main__":
    mp.set_start_method("forkserver")

    from loguru import logger

    mp_context = mp.get_context("forkserver")

    logger.remove()
    logger.configure(
        handlers=[
            {"sink": sys.stderr, "enqueue": True,"context":mp_context},
            {
                "sink": "{time}.log",
                "enqueue": True,
                "context": mp_context,
            },
        ]
    )

def _processpool_initializer(parent_logger):
    from loguru import logger
    # HACK: Workaround loguru limitations when it comes to forkspawns / spawn
    logger._core = parent_logger._core  # type: ignore

def noop():
    
    # within the pull function, this points to the correct logger now.
    from loguru import logger
    print(logger._core.handlers)
    logger.info("Noop!")

if __name__ == "__main__":
    with mp_context.Pool(processes=1, initializer=_processpool_initializer,initargs=(logger,)) as pool:
        pool.apply_async(noop).get()
```

Seems like this works. not entirely elegant but it works.

**Comment by Delgan** [comment]
Hi @KaraKaraWitch.

The `logger` indeed needs to be inherited using the `initializer` argument of `Pool()`.

It's explained here in the docs: [Compatibility with multiprocessing using enqueue argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument).

Usually, that also requires updating the global instance of the `logger` in your child process. Possibly:

```python
from loguru import logger

def update_global_logger(logger_):
    logger.__dict__ = logger_.__dict__.copy()

if __name__ == "__main__":
    with mp_context.Pool(processes=1, initializer=_processpool_initializer,initargs=(logger,)) as pool:
        pool.apply_async(noop).get()
```

I agree this looks hacky. I'll provide an helper method `logger.reinstall()` in the next version.
