### ISSUE TITLE
FileSink Error when running from terminal

### ISSUE THREAD

**Issue by rclapp** [Delgan/loguru#242]
During testing I hit an error that I need some help solving. The odd thing is that this works okay in my IDE, but fails with the following error in terminal. I've validated all the interpreter and package settings are the same. 

Logging is set up as follows:
 ```python
    '''
        Initializes logging for the program. If a log file has been specified a queue handler is enabled.
    '''

    # Logging Set-Up Loguru
    logger.remove()
    format = "<green>{time} | {elapsed}</green> | {level} | <blue>{module}:{function} | {process}:{thread}</blue> | <level>{message}</level>"

    #Intercept Logging Messages
    logging.basicConfig(handlers=[InterceptHandler()], level=0)

    if arguments["debug"]:
        logger.add(sys.stdout, level='DEBUG', filter='__main__', backtrace=True, diagnose=True, enqueue=True, format=format, colorize=True)
    else:
        logger.add(sys.stdout, level='INFO', filter='__main__', backtrace=True, diagnose=True, enqueue=True, format=format, colorize=True)

    try:
        os.makedirs(logfile.parents[0], exist_ok=True)
        logger.info(f"Directory {logfile.parents[0]} created successfully")
    except OSError as error:
        logger.exception(f"Directory {logfile.parent()} can not be created", exc_info=True)

    if logfile is not None:
        try:
            if arguments["debug"]:
                logger.add(logfile, level="DEBUG", retention="10 days", backtrace=True, diagnose=True, enqueue=True, format=format, colorize=True)
            else:
                logger.add(logfile, level="INFO", retention="10 days", backtrace=True, diagnose=True, enqueue=True, format=format, colorize=True)

        except Exception as e:

            logger.exception('Failed to add file handlers', exc_info=True)

    logging.info('logging setup complete')
```

Error:

```python
--- Logging error in Loguru Handler #2 ---
Record was: {'elapsed': datetime.timedelta(seconds=1, microseconds=46842), 'exception': None, 'extra': {}, 'file': '__init__.py', 'function': 'info', 'level': 'Level 20', 'line': 1992, 'message': 'logging setup complete', 'module': '__init__', 'name': 'logging', 'process': '2016', 'thread': '14716', 'time': datetime(2020, 4, 13, 13, 12, 17, 268459, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200), 'Pacific Daylight Time'))}

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\loguru\_handler.py", line 253, in _queued_writer
    self._writer(message)
  File "D:\Python37\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "D:\Python37\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "D:\Python37\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "D:\Python37\lib\site-packages\colorama\ansitowin32.py", line 196, in write_plain_text
    self.wrapped.flush()

AttributeError: 'FileSink' object has no attribute 'flush'

--- End of logging error ---
```

I looked at the FileSink class and as the error says it doesn't have a flush attribute, but I am not sure why colorama is calling that.

**Comment by Delgan** [comment]
Hey @rclapp!

I can't reproduce the problem, but it seems related to [`should_wrap()`](https://github.com/Delgan/loguru/blob/e2a337a40d1fb627d88cbe05d61b733b0ff1c92e/loguru/_colorama.py#L21-L27) returning `True` while it shouldn't for file sinks. 

Do you need `colorize=True` for our file sinks? The error should go away if you set it to `False`.

**Comment by rclapp** [comment]
Good call, for the file sink I certainly don't need color. Let me give that a shot.

Ryan Clapp
AWS Business Systems
Sr. Manager

Sent from my mobile device

On Apr 13, 2020 11:06 PM, Delgan <notifications@github.com> wrote:

Hey @rclapp<https://github.com/rclapp>!

I can't reproduce the problem, but it seems related to should_wrap()<https://github.com/Delgan/loguru/blob/e2a337a40d1fb627d88cbe05d61b733b0ff1c92e/loguru/_colorama.py#L21-L27> returning True while it shouldn't for file sinks.

Do you need colorize=True for our file sinks? The error should go away if you set it to False.

-

**Comment by rclapp** [comment]
That did the trick.

**Comment by Delgan** [comment]
Ok, it looks you're using `v0.3.x`, which explains why I was confused trying to understand the bug. :smile: 

I advise you to upgrade to `v0.4.1` if possible, this bug and others have been fixed. :+1:
