### ISSUE TITLE
possible regression in intergration with sentry in version >=0.4.0

### ISSUE THREAD

**Issue by itraviv** [Delgan/loguru#304]
with loguru versions < 0.4.0 the addition of sentry handlers (sentry-sdk==0.16.0):
```python
h1 =   {
            'sink': sentry_sdk.integrations.logging.EventHandler,
            'level': logging.ERROR,
            'format': '{message}',
            'backtrace': False,
        }
h2 =   {
            'sink': sentry_sdk.integrations.logging.BreadcrumbHandler,
            'level': logging.DEBUG,
            'format': '{message}',
            'backtrace': False,
        }
   
logger.configure(handlers=[h1, h2],)
```
results in:
```
2020-08-05 20:34:00.846 | INFO     | main:10 - test
```
with loguru version >= 0.4.0 this results in:
```
--- Logging error in Loguru Handler #3 ---
Record was: {'elapsed': datetime.timedelta(0, 0, 216902), 'exception': None, 'file': (name='logger.py', path='/home/user/test/logger.py'), 'function': 'main', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 10, 'message': 'test', 'module': 'logger', 'name': 'cfg.logger', 'process': (id=11374, name='MainProcess'), 'thread': (id=139927630493504, name='MainThread'), 'time': datetime(2020, 8, 5, 20, 34, 11, 930226, tzinfo=datetime.timezone(datetime.timedelta(0, 10800), 'IDT'))}
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/loguru/_handler.py", line 153, in emit
    self._sink.write(str_record)
  File "/usr/local/lib/python3.6/dist-packages/loguru/_simple_sinks.py", line 106, in write
    self._function(message)
  File "/usr/lib/python3.6/logging/__init__.py", line 778, in __init__
    self.level = _checkLevel(level)
  File "/usr/lib/python3.6/logging/__init__.py", line 195, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: 'test\n'
--- End of logging error ---
```
and breaks the integration where the levels were correctly defined. i have also tried to define it using an str representation like `"INFO"` or `"ERROR"` having the same behavior
python3.6.9

**Comment by Delgan** [comment]
Hey @itraviv.

Since `v0.4.0`, it's  no longer possible to use a actual class as a sink, it is better to pass the instance directly. It was a bad design decision in the first place, so I removed it. Sorry it caused a regression in your program.

The workaround is very easy: use `'sink': sentry_sdk.integrations.logging.EventHandler()` instead (same thing for `BreadcrumbHandler()` obviously). After that, I think it should work fine. :wink:

**Comment by itraviv** [comment]
it is indeed working fine.
Thanks!
