### ISSUE TITLE
I got error with loguru when run with gevent (monkey.pathc_all())

### ISSUE THREAD

**Issue by bo-ke** [Delgan/loguru#352]
I use `loguru==0.5.3` and I got the error
```shell
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "/data01/kebo/go-learning/monkey_test.py", line 12, in http_request
    logger.info(url)
  File "/data01/kebo/anaconda3/lib/python3.6/site-packages/loguru/_logger.py", line 1971, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File "/data01/kebo/anaconda3/lib/python3.6/site-packages/loguru/_logger.py", line 1912, in _log
    "extra": {**core.extra, **context.get(), **extra},
  File "/data01/kebo/anaconda3/lib/python3.6/site-packages/contextvars/__init__.py", line 96, in get
    return ctx[self]
  File "/data01/kebo/anaconda3/lib/python3.6/site-packages/contextvars/__init__.py", line 51, in __getitem__
    "a ContextVar key was expected, got {!r}".format(var))
TypeError: a ContextVar key was expected, got <ContextVar name='loguru_context' default={} at 2b5dbd70b9b0>
2020-10-17T08:29:22Z <Greenlet at 0x2b5dbde87748: http_request('http://trello.com')> failed with TypeError
```
This is my code
```python
from loguru import logger
import time
monkey.patch_all()

def http_request(url):
    res = requests.get(url)
    logger.info(url)
    return res.text

if __name__ == '__main__':
    start = time.time()
    g_list = []
    g_list.append(gevent.spawn(http_request, "http://trello.com"))
    g_list.append(gevent.spawn(http_request, "http://google.com"))
    g_list.append(gevent.spawn(http_request, "http://trello.com"))
    g_list.append(gevent.spawn(http_request, "http://google.com"))
    g_list.append(gevent.spawn(http_request, "http://trello.com"))
    g_list.append(gevent.spawn(http_request, "http://google.com"))
    g_list.append(gevent.spawn(http_request, "http://trello.com"))

    gevent.joinall(g_list)
    m, n = g_list[0].value, g_list[1].value
    print(time.time() - start)
```
And when I delete `monkey.patch_all()`, it's work

**Comment by Delgan** [comment]
Hi.

As the error message mentions `contextvars`, did you try calling `monkey.patch_all(contextvars=False)` instead?

**Comment by Delgan** [comment]
Another possibility is to import `loguru` **after** having called `monkey.patch_all()`.

**Comment by bo-ke** [comment]
@Delgan thanks for your reply, I understand the reason and I tried `monkey.patch_all(contextvars=False)` or import `loguru` after `called monkey.patch_all()`, both of them worked.
