### ISSUE TITLE
PyInstaller bundled app: Failing to get source code with exceptions

### ISSUE THREAD

**Issue by JulianOrteil** [Delgan/loguru#364]
Hey @Delgan,

I'm not too sure if this is a loguru or PyInstaller issue, but I figured I'd start here.

I'm still working on that app from my previous tickets and am running into an issue when it is bundled. When an exception occurs within the app while bundled (i.e. running from EXE), I am not seeing any source code being recorded by loguru from the exception. I tried this in a fresh environment (conda) with only loguru 0.5.3 and pyinstaller 4.0 the installed 3rd party libraries and got the same thing. I tried a different app with just a single, tiny file in both the original and new environment and still got the issue.

Here is an example output from the other application
```
2020-11-12 14:23:31.082 | INFO     | __main__:main:5 - Here is a message
2020-11-12 14:23:31.084 | ERROR    | __main__:<module>:10 - An error has been caught in function '<module>', process 'MainProcess' (8008), thread 'MainThread' (2504):
Traceback (most recent call last):

> File "main.py", line 10, in <module>

  File "main.py", line 7, in main

ValueError: Test error
```

As you can see, this is the default configuration for loguru. Anyways, here is the source code:

```
from loguru import logger

@logger.catch
def main():
    logger.info("Here is a message")

    raise ValueError("Test error")

if __name__ == "__main__":
    main()
```
Put that into a file named `main.py` and then run the following command with pyinstaller:
`pyinstaller main.py`

Then run the bundled exe and it should produce the issue.

Let me know if there is anything else I can provide.
Jules

**Comment by JulianOrteil** [comment]
When I run the app from src, this is what I see:

```
2020-11-12 18:21:17.564 | INFO     | __main__:main:5 - Here is a message
2020-11-12 18:21:17.574 | ERROR    | __main__:<module>:10 - An error has been caught in function '<module>', process 'MainProcess' (9844), thread 'MainThread' 
(14432):
Traceback (most recent call last):

  File "C:\Users\jules\.conda\envs\app\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...  
           │         └ <code object <module> at 0x0000025F71445030, file "c:\Users\jules\.vscode\extensions\ms-python.python-2020.11.35836...        
           └ <function _run_code at 0x0000025F7149D9D0>

  File "C:\Users\jules\.conda\envs\app\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x0000025F71445030, file "c:\Users\jules\.vscode\extensions\ms-python.python-2020.11.35836...

  File "c:\Users\jules\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>       
    cli.main()
    │   └ <function main at 0x0000025F73E6B160>
    └ <module 'debugpy.server.cli' from 'c:\\Users\\jules\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pytho...

  File "c:\Users\jules\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
    └ <function run_file at 0x0000025F73E69EE0>

  File "c:\Users\jules\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
    │     │        │       │                │      └ <function force_str at 0x0000025F716B44C0>
    │     │        │       │                └ <module 'debugpy.common.compat' from 'c:\\Users\\jules\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\py...
    │     │        │       └ 'c:\\Users\\jules\\Documents\\app\\main.py'
    │     │        └ <debugpy.server.cli.Options object at 0x0000025F73E33E50>
    │     └ <function run_path at 0x0000025F714C81F0>
    └ <module 'runpy' from 'C:\\Users\\jules\\.conda\\envs\\app\\lib\\runpy.py'>

  File "C:\Users\jules\.conda\envs\app\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
           │                │     │             └ '__main__'
           │                │     └ None
           │                └ <code object <module> at 0x0000025F0AECE240, file "c:\Users\jules\Documents\app\main.py", line 1>
           └ <function _run_module_code at 0x0000025F714BDE50>

  File "C:\Users\jules\.conda\envs\app\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
    │         │     │            └ None
    │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'c:\\Users\\da...
    │         └ <code object <module> at 0x0000025F0AECE240, file "c:\Users\jules\Documents\app\main.py", line 1>
    └ <function _run_code at 0x0000025F7149D9D0>

  File "C:\Users\jules\.conda\envs\app\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'c:\\Users\\da...
         └ <code object <module> at 0x0000025F0AECE240, file "c:\Users\jules\Documents\app\main.py", line 1>

> File "c:\Users\jules\Documents\app\main.py", line 10, in <module>
    main()
    └ <function main at 0x0000025F0AEDD0D0>

  File "c:\Users\jules\Documents\app\main.py", line 7, in main
    raise ValueError("If this works, unknown issue")

ValueError: Test error
```

**Comment by Delgan** [comment]
Hello.

This looks very similar to this issue: #250
Can you confirm that this is the same problem?

It seems you need to the add the source code to the bundled application using `--add-data=main.py;.`.

**Comment by JulianOrteil** [comment]
I see, I think Google must be broken as I couldn't find anything related to this :/

Thank you for the pointer to a solution as always @Delgan .
I wouldn't feel comfortable with the current environment this app would run in with the source code being available, but thank you anyways. 👍

**Comment by zhfkt** [comment]
> Hello.
> 
> This looks very similar to this issue: #250 Can you confirm that this is the same problem?
> 
> It seems you need to the add the source code to the bundled application using `--add-data=main.py;.`.

This solution seems not sensible for me because I have more than 200+ python files. It is not possible to carry 200 source files which just to support printing loguru in details

**Comment by Delgan** [comment]
@zhfkt Unfortunately I'm not aware of any solution without bundling data. As far as I know, the Python exception formatter needs the source file to retrieve and display the source lines.
