### ISSUE TITLE
Cannot use loguru handlers with spark due to lru_cache

### ISSUE THREAD

**Issue by dzanaga** [Delgan/loguru#386]
I am running an application on a spark cluster.

The driver creates a telegram handler and adds it to loguru.
In older versions of loguru (e.g. 0.3.2) this was working.
In more recent versions of loguru, when the driver starts pickling objects to send them to the executors there are issues with unpickable objects, for example I get this error when adding the telegram handler:
`Can't pickle <functools._lru_cache_wrapper object at 0x7f3d8688f4b0>: it's not the same object as urllib.parse.urljoin`

**Comment by Delgan** [comment]
Can you please share the code where are configured your handlers?

Also, do you know from which logging message this issue comes from?

**Comment by dzanaga** [comment]
Sorry it took a while.

This is the python code:
```
import os
import random

from loguru import logger
from notifiers.logging import NotificationHandler
import pyspark


if __name__ == '__main__':

    TELEGRAM_TOKEN = os.environ.get('TELEGRAM_TOKEN')
    TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID')

    logger.info(f"Token: {TELEGRAM_TOKEN}")
    logger.info(f"Chat id: {TELEGRAM_CHAT_ID}")

    params = dict(token=TELEGRAM_TOKEN, chat_id=TELEGRAM_CHAT_ID)
    telegram_handler = NotificationHandler("telegram", defaults=params)
    telegram_sink = logger.add(telegram_handler)

    sc = pyspark.SparkContext(appName="EstimatePi")

    def inside(p):
        logger.info(p)
        x, y = random.random(), random.random()
        return x*x + y*y < 1

    logger.info("Computing Pi")
    NUM_SAMPLES = 100000
    count = sc.parallelize(range(0, NUM_SAMPLES)) \
        .filter(inside).count()

    print("Pi is roughly %f" % (4.0 * count / NUM_SAMPLES))
    sc.stop()
```
And the full error is:
```
2021-01-28 12:50:02.572 | INFO     | __main__:<module>:28 - Computing Pi
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/notifiers/logging.py", line 50, in emit
    self.provider.notify(raise_on_errors=True, **data)
  File "/usr/lib/python3.7/site-packages/notifiers/core.py", line 306, in notify
    rsp.raise_on_errors()
  File "/usr/lib/python3.7/site-packages/notifiers/core.py", line 64, in raise_on_errors
    response=self.response,
notifiers.exceptions.NotificationError: Notification errors: Unauthorized
Call stack:
  File "app/app/entrypoint.py", line 28, in <module>
    logger.info("Computing Pi")
  File "/usr/lib/python3.7/site-packages/loguru/_logger.py", line 1971, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File "/usr/lib/python3.7/site-packages/loguru/_logger.py", line 1959, in _log
    handler.emit(log_record, level_id, from_decorator, raw, colored_message)
  File "/usr/lib/python3.7/site-packages/loguru/_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "/usr/lib/python3.7/site-packages/loguru/_simple_sinks.py", line 60, in write
    self._handler.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/lib/python3.7/site-packages/notifiers/logging.py", line 52, in emit
    self.handleError(record)
Message: '2021-01-28 12:50:02.572 | INFO     | __main__:<module>:28 - Computing Pi'
Arguments: ()
Traceback (most recent call last):
  File "app/app/entrypoint.py", line 31, in <module>
    .filter(inside).count()
  File "/usr/lib/python3.7/site-packages/pyspark/rdd.py", line 1141, in count
    return self.mapPartitions(lambda i: [sum(1 for _ in i)]).sum()
  File "/usr/lib/python3.7/site-packages/pyspark/rdd.py", line 1132, in sum
    return self.mapPartitions(lambda x: [sum(x)]).fold(0, operator.add)
  File "/usr/lib/python3.7/site-packages/pyspark/rdd.py", line 1003, in fold
    vals = self.mapPartitions(func).collect()
  File "/usr/lib/python3.7/site-packages/pyspark/rdd.py", line 889, in collect
    sock_info = self.ctx._jvm.PythonRDD.collectAndServe(self._jrdd.rdd())
  File "/usr/lib/python3.7/site-packages/pyspark/rdd.py", line 2629, in _jrdd
    self._jrdd_deserializer, profiler)
  File "/usr/lib/python3.7/site-packages/pyspark/rdd.py", line 2517, in _wrap_function
    pickled_command, broadcast_vars, env, includes = _prepare_for_python_RDD(sc, command)
  File "/usr/lib/python3.7/site-packages/pyspark/rdd.py", line 2503, in _prepare_for_python_RDD
    pickled_command = ser.dumps(command)
  File "/usr/lib/python3.7/site-packages/pyspark/serializers.py", line 468, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 1097, in dumps
    cp.dump(obj)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 357, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 501, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 730, in save_function_tuple
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 501, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 730, in save_function_tuple
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 501, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 730, in save_function_tuple
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 501, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 730, in save_function_tuple
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 501, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 730, in save_function_tuple
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.7/pickle.py", line 846, in _batch_appends
    save(tmp[0])
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 501, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 730, in save_function_tuple
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.7/pickle.py", line 846, in _batch_appends
    save(tmp[0])
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 496, in save_function
    self.save_function_tuple(obj)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 730, in save_function_tuple
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 890, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 535, in save
    self.save_global(obj, rv)
  File "/usr/lib/python3.7/site-packages/pyspark/cloudpickle.py", line 841, in save_global
    return Pickler.save_global(self, obj, name=name)
  File "/usr/lib/python3.7/pickle.py", line 965, in save_global
    (obj, module_name, name))
_pickle.PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x7f0f902e02d0>: it's not the same object as urllib.parse.urljoin
```
No error occurs using `loguru==0.3.2`.
To replicate, since you need the spark stack I created a repo with instructions to run the example and via docker:
https://github.com/dzanaga/loguru-spark-test

**Comment by Delgan** [comment]
Hey @dzanaga! 

It took me a bit of time to get into it too. Thanks to your fully reproducible example, I was able to quickly find the cause of the problem. Thank you for taking the time to create a dedicated repository with clear instructions! :+1: 
Basically, the regression was introduced by commit 14848a4f8268d169d0353d4380dbe9215cf90972 as part of #157.

What happened is that the `logger` instance now contains non-picklable objects like `threading.Lock` as member variable while they were previously more like global variables. It was required to fix others caveat of `multiprocessing` with Loguru, so I can't really change the way it is.

I don't know PySpark so maybe you can solve the problem better than me. What I noticed is that the function passed to `parallelize().filter()` must be somehow serialized. However, if the function contains non-picklable object, it will fail. I was able to reproduce the error without introducing `loguru` nor `notifiers`.

```python
import threading

import pyspark

if __name__ == '__main__':
    sc = pyspark.SparkContext(appName="EstimatePi")
    
    lock = threading.Lock()

    def inside(p):
        print(lock)
        return True

    print("Computing Pi")
    
    NUM_SAMPLES = 100000
    count = sc.parallelize(range(0, NUM_SAMPLES)).filter(inside).count()

    print("Pi is roughly %f" % (4.0 * count / NUM_SAMPLES))

    sc.stop()
```

Because `inside()` needs a reference to the non-picklable `lock`, it generates a `_pickle.PicklingError: Could not serialize object: TypeError: cannot pickle '_thread.lock' object` exception.

Some `multiprocessing` methods allow to inherit an non-pickable object using arguments suck as `initializer` and `initargs` (more info [in the documentation](https://loguru.readthedocs.io/en/latest/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument)). Do you know if it exists something similar with PySpark?

What we need is a way to specify that the `logger` should not be serialized by the [`SparkContext`](https://spark.apache.org/docs/latest/api/python/pyspark.html#pyspark.SparkContext) here: https://github.com/apache/spark/blob/098f2268e4ad43dd9453ada91161ea428dd57d16/python/pyspark/rdd.py#L2816

**Comment by dzanaga** [comment]
Hi @Delgan, thanks for looking into.

I am no Spark expert, but as I understand it, because Spark is used for distributed computing, you do need to be able to pickle/serialize everything that needs to be sent to the executors. As opposed to `multiprocessing`, Spark can distribute, and usually that's its purpose to different machines in a cluster. So this is an additional complexity over `multiprocessing` and I am not completely sure, but I think there is no way of sending locks or avoid pickling to other machines, it probably doesn't make sense as well.

So in fact, reasoning on it, I realize that previously to the change you made in #157 , it was working but actually not in the expected way probably when doing distributed computing. So what happened was that sinks like the telegram one were not sent to the executors on other machines, and `loguru` would just behave independently from the main process and driver machine, generating logs to stderr and eventually to files that you would add on the local machine. This is probably not the expected behavior, as ideally you would want all the executors to be aware of the sinks added on the driver. But if sinks cannot be serialized then this is not possible.

So I think probably there is here a limitation in the usage of `loguru` with Spark. I'll do a bit more of testing and see if I manage to find a workaround, I'll then add my findings here, and I guess this could probably be added to the docs under `Compatibility with Spark` or similar.

**Comment by Delgan** [comment]
Yes, in fact my comment was incorrect. I assumed that it was not possible to use the `logger` inside Spark, due to an internal lock used by Loguru. But obviously this is not the case, since it works with `stderr` only. The `logger` [is picklable](https://github.com/Delgan/loguru/blob/master/loguru/_logger.py#L185-L192) as long as the added handlers are picklable too, but `NotificationHandler` isn't.

Can you try to replace `NotificationHandler` with something like that please:

```python
def telegram_sink(message):
    notifier = notifiers.get_notifier("telegram")
    notifier.notify(message, token=TELEGRAM_TOKEN, chat_id=TELEGRAM_CHAT_ID)
```

**Comment by Delgan** [comment]
@dzanaga Can you confirm the `telegram_sink()` function solved the issue?

**Comment by dzanaga** [comment]
@Delgan didn't try yet, will test asap, thanks

**Comment by dzanaga** [comment]
It works! Thanks for the solution.
