### ISSUE TITLE
enque causes _pickle.PicklingError: Can't pickle <function <lambda> at 0x000001F6BACAC9D0>: attribute lookup <lambda> on __main__ failed

### ISSUE THREAD

**Issue by chwba** [Delgan/loguru#399]
```
# Windows implementation
import multiprocessing
from loguru import logger

def my_process(logger_):
    logger_.info("Executing function in child process")
    logger_.complete()

if __name__ == "__main__":
    logger.remove()  # Default "sys.stderr" sink is not picklable
    logger.add(stderr, filter=lambda record: "do_stuff" in record["extra"], enqueue=True)

    process = multiprocessing.Process(target=my_process, args=(logger, ))
    process.start()
    process.join()

    logger.info("Done")
```

```
Traceback (most recent call last):
  File "C:\Users\Administrator\git\playwright_generator\ext\chwba.py", line 188, in <module>
    process.start()
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x000001F6BACAC9D0>: attribute lookup <lambda> on __main__ failed
```

**Comment by Delgan** [comment]
Indeed, Loguru requires the handlers and its arguments to be "picklable". I prefer not to introduce a new dependency, event if this means one can't use `lambda` with `multiprocessing` on Windows. A workaround exists, simply use a named function:

```python
def my_filter(record):
    return "do_stuff" in record["extra"]

logger.add(stderr, filter=my_filter, enqueue=True)
```

**Comment by chwba** [comment]
I tried to implement it this way, now I am getting:
```
--- Logging error in Loguru Handler #1 ---
Record was: None
Traceback (most recent call last):
  File "C:\Users\Administrator\git\playwright_generator\venv\lib\site-packages\loguru\_handler.py", line 270, in _queued_writer
    message = queue.get()
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.9.1\lib\multiprocessing\queues.py", line 368, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Administrator\git\playwright_generator\venv\lib\site-packages\loguru\_recattrs.py", line 77, in _from_pickled_value
    value = pickle.loads(pickled_value)
TypeError: __init__() missing 1 required keyword-only argument: 'request'
--- End of logging error ---
```

**Comment by Delgan** [comment]
This `TypeError` with missing required argument happens when some object contained in the logged `record` can't be serialized.

Maybe it's related to `logger.complete()` but I'm not so sure. Considering it's happening occasionally, this also could be due to a caught `Exception` with a custom subclass not implementing `__reduce__` properly. 

This is not the first time this problem is reported:
* https://github.com/Delgan/loguru/issues/329
* https://github.com/Delgan/loguru/issues/342
* https://github.com/Delgan/loguru/issues/357

 I will fix it by replacing the `Exception` value with `None` if it can't be pickled. 

If you use `logger.exception()` from where you know this issue comes from, you may need to add a `try / catch` instead as explained in the linked issues.

**Comment by chwba** [comment]
I noticed when I run more processes than just one or two concurrentlxy this happens a lot more often - even with correctly awaiting logger.complete() - A very good solution would be to make the enqueue argument compatible to using the multiprocess library which uses dill for pickling - With this one there were no errors at least, though there was weird behaviour with loguru not properly logging to a file with multiple sinks to multiple files added and then the log called from within a running process.

**Comment by Delgan** [comment]
I don't want to add `dill` as a dependency (although it's a very good library) to fix only part of the possible edge cases. The proper solution is to make the object (un)picklable or to avoid logging it. However I agree the current logging error message is not helpful at all. I would like to improve that, but it seems a bit complicated (because the exception happens during de-serialization in a thread).

I would suggest adding a debugging sink in charge of serializing and then de-serializing the log messages. This would act similarly to `enqueue=True` and hence should cause the same `TypeError`, but the resulting traceback should indicate the source.

```python
import pickle

def debugging_sink(message):
    pickle.loads(pickle.dumps(message))

logger.add(debugging_sink)
```

**Comment by chwba** [comment]
Thanks you, I will use this to investigate further. - Note: What I meant by "adding support for dill to `enqueue=True`" is that one can use the https://github.com/uqfoundation/multiprocess library (which uses dill) instead of the built-in multiprocessing while having `enqueue=True` set. Currently if one does that it will drop an exception that `SimpleQueue  objects should only be shared through inheritance`. - If one sets enqueue=False using the multiprocess library loguru does work but there are some unpredictable drawbacks, such as that a sink that should log to a file (filtered by a record in extra) does not log into the file from inside a process.

**Comment by Delgan** [comment]
Ok I see. Indeed, it's annoying that `loguru` can't be used easily with the `multiprocess` library.

I tried to find solutions but I could not find any elegant workaround as it seems to require modifying the objects (`SimpleQueue`, `Lock`, `Condition`, etc.) used internally. It's possible to "patch" the library used internally before importing the `logger`, but obviously I do not  really recommend it: `loguru._handler.multiprocessing = multiprocess`.

At that point, I think the best is to create a custom `Handler` based on `multiprocess` and re-implement the `enqueue` behavior. This could belong to another library and be easily imported like [multiprocessin-logging](https://github.com/jruere/multiprocessing-logging) for example.
