### ISSUE TITLE
Test failures with pytest 6.2.2

### ISSUE THREAD

**Issue by rmcgibbo** [Delgan/loguru#417]
The NixOS CI system shows that loguru's tests recently started failing. I was able to git bisect this to a bump of pytest from 6.1.2 to 6.2.2. https://hydra.nixos.org/job/nixpkgs/trunk/python38Packages.loguru.x86_64-linux

I did look through the github issues, and wasn't able to find something that looked similar, so I thought I'd bring this to your attention.

Here are the relevant errors
```
=================================== FAILURES ===================================
_____________________ test_not_caught_exception_queue_get ______________________

writer = <function writer.<locals>.w at 0x7ffff522ba60>
capsys = <_pytest.capture.CaptureFixture object at 0x7ffff520a3d0>

    def test_not_caught_exception_queue_get(writer, capsys):
        logger.add(writer, enqueue=True, catch=False, format="{message}")
    
        logger.info("It's fine")
        logger.bind(broken=NotUnpicklable()).info("Bye bye...")
        logger.info("It's not fine")
        logger.remove()
    
        out, err = capsys.readouterr()
        lines = err.strip().splitlines()
        assert writer.read() == "It's fine\n"
        assert out == ""
>       assert lines[0].startswith("Exception")
E       IndexError: list index out of range

tests/test_add_option_enqueue.py:152: IndexError
_____________________ test_not_caught_exception_sink_write _____________________

capsys = <_pytest.capture.CaptureFixture object at 0x7ffff520a100>

    def test_not_caught_exception_sink_write(capsys):
        logger.add(NotWritable(), enqueue=True, catch=False, format="{message}")
    
        logger.info("It's fine")
        logger.bind(fail=True).info("Bye bye...")
        logger.info("It's not fine")
        logger.remove()
    
        out, err = capsys.readouterr()
        lines = err.strip().splitlines()
        assert out == "It's fine\n"
>       assert lines[0].startswith("Exception")
E       IndexError: list index out of range

tests/test_add_option_enqueue.py:167: IndexError
=============================== warnings summary ===============================
tests/test_add_option_catch.py::test_broken_sink_not_caught_enqueue
  /nix/store/8g3m1rjz0xzlwiwlli02dadadf7sdm5c-python3.8-pytest-6.2.2/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledTh>
  
  Traceback (most recent call last):
    File "/nix/store/v9kcvgisjyrjnzhxq1kpsp1al9iif5q0-python3-3.8.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/nix/store/v9kcvgisjyrjnzhxq1kpsp1al9iif5q0-python3-3.8.8/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/build/loguru-0.5.3/loguru/_handler.py", line 287, in _queued_writer
      self._sink.write(message)
    File "/build/loguru-0.5.3/loguru/_simple_sinks.py", line 119, in write
      self._function(message)
    File "/build/loguru-0.5.3/tests/test_add_option_catch.py", line 131, in broken_sink
      raise ValueError("Nop")
  ValueError: Nop
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/test_add_option_enqueue.py::test_not_caught_exception_queue_get
  /nix/store/8g3m1rjz0xzlwiwlli02dadadf7sdm5c-python3.8-pytest-6.2.2/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledTh>
  
  Traceback (most recent call last):
    File "/nix/store/v9kcvgisjyrjnzhxq1kpsp1al9iif5q0-python3-3.8.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/nix/store/v9kcvgisjyrjnzhxq1kpsp1al9iif5q0-python3-3.8.8/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/build/loguru-0.5.3/loguru/_handler.py", line 270, in _queued_writer
      message = queue.get()
    File "/nix/store/v9kcvgisjyrjnzhxq1kpsp1al9iif5q0-python3-3.8.8/lib/python3.8/multiprocessing/queues.py", line 358, in get
      return _ForkingPickler.loads(res)
    File "/build/loguru-0.5.3/tests/test_add_option_enqueue.py", line 22, in __setstate__
      raise pickle.UnpicklingError("You shall not de-serialize me!")
  _pickle.UnpicklingError: You shall not de-serialize me!
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/test_add_option_enqueue.py::test_not_caught_exception_sink_write
  /nix/store/8g3m1rjz0xzlwiwlli02dadadf7sdm5c-python3.8-pytest-6.2.2/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledTh>
  
  Traceback (most recent call last):
    File "/nix/store/v9kcvgisjyrjnzhxq1kpsp1al9iif5q0-python3-3.8.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/nix/store/v9kcvgisjyrjnzhxq1kpsp1al9iif5q0-python3-3.8.8/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/build/loguru-0.5.3/loguru/_handler.py", line 287, in _queued_writer
      self._sink.write(message)
    File "/build/loguru-0.5.3/loguru/_simple_sinks.py", line 26, in write
      self._stream.write(message)
    File "/build/loguru-0.5.3/tests/test_add_option_enqueue.py", line 28, in write
      raise RuntimeError("You asked me to fail...")
  RuntimeError: You asked me to fail...
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ===========================
```

**Comment by rmcgibbo** [comment]
It looks like this was fixed in https://github.com/Delgan/loguru/commit/31cf758ee9d22dbfa125f38153782fe20ac9dce5

**Comment by Delgan** [comment]
Thank you for taking the time to investigate and report the problem anyway. :+1:
I fixed it some times ago, yeah, but it's not released yet.

**Comment by rmcgibbo** [comment]
(It's a great library. I'm looking forward to the next release, especially for python3.9 support.)
