### ISSUE TITLE
Incompatibility with joblib

### ISSUE THREAD

**Issue by hadim** [Delgan/loguru#498]
joblib with its `loky` backend is widely used for distributed computing. Without going into the details the `loky` backend has a lot of advantages over the `multiprocessing` backend.

Loguru does not seem to work with `jobli`/`loky` because of a pickle issue. I tried to apply the hints from the doc without success.

I was wondering whether it's possible to make loguru compatible with joblib:

```python
import sys
from joblib import Parallel, delayed
from loguru import logger


def func_async():
    logger.info("Hello")

# logger.remove()
# logger.add(sys.stderr, enqueue=True)
    
args = [delayed(func_async)() for _ in range(100)]

p = Parallel(n_jobs=16, backend="loky")
results = p(args)
```

The error:

```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/joblib/externals/loky/backend/queues.py", line 153, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 271, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/hadim/local/conda/envs/circus/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.lock' object
"""

The above exception was the direct cause of the following exception:

PicklingError                             Traceback (most recent call last)
/tmp/ipykernel_2094805/2576140850.py in <module>
     13 
     14 p = Parallel(n_jobs=16, backend="loky")
---> 15 results = p(args)

~/local/conda/envs/circus/lib/python3.8/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~/local/conda/envs/circus/lib/python3.8/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~/local/conda/envs/circus/lib/python3.8/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/local/conda/envs/circus/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    442                     raise CancelledError()
    443                 elif self._state == FINISHED:
--> 444                     return self.__get_result()
    445                 else:
    446                     raise TimeoutError()

~/local/conda/envs/circus/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    387         if self._exception:
    388             try:
--> 389                 raise self._exception
    390             finally:
    391                 # Break a reference cycle with the exception in self._exception

PicklingError: Could not pickle the task to send it to the workers.
```

**Comment by Delgan** [comment]
Hi @hadim.

Which version of Loguru are you using?

I tested in on my computer and it works fine (Linux, Python 3.9.2, joblib 1.0.1, loguru 0.5.3).

**Comment by hadim** [comment]
My setup is the same as yours except I have Python 3.8.10.

I think I found the issue. I was testing within a Jupyter notebook while executing the snippet from a script works as excepted.

That being said I am a bit surprised because I still see the error in my production scripts that are all executed in a regular terminal (no notebook). Those are too complex to reproduce and that's why I have created the small snippet.

Can you imagine any corner cases why it would fail with joblib/loky?

**Comment by Delgan** [comment]
So, I was able to reproduce the issue using a Jupyter notebook.

I can't tell if this is related to the problem you're facing in production.

This happens due to an internal `Lock` used by `sys.stderr`, I guess. Here is a reproducible example without involving Loguru:

```python
import sys
from joblib import Parallel, delayed

output = sys.stderr

def func_async():
    output.write("Test")
    
args = [delayed(func_async)() for _ in range(10)]

p = Parallel(n_jobs=16, backend="loky")
results = p(args)
``` 

The thing is that the `logger` is configured with the `sys.stderr` handler by default which can't be pickled. 

I see three possible workarounds:
* Call a setup function once the worker has been started, so that you could add the `sys.stderr` before running the job and thus avoiding the need to pickle it. In this case, each worker will have its own handler but shared resources won't be protected, which is not ideal.
* Replace the default handler with a pickable one. Wrapping the output with `logger.add(lambda m: sys.stderr.write(m))
` after calling `logger.remove()` seems to do the trick. Again, at worker initialization, handler will be deep-copied during pickling, so `sys.stderr` won't be protected from parallel access.
* Find a way to pass the `logger` and its handlers by making the workers inherit from it instead of pickling it (just like it's done with `args` of [`Process`](https://docs.python.org/fr/3/library/multiprocessing.html#multiprocessing.Process)).

I don't know Joblib API, maybe you can find a clean way to pass the handler by inheritance without pickle?

**Comment by hadim** [comment]
Thanks for looking into it. This is very insightful. I don't see any clean ways to fix it for now. Passing it as an args will probably call a pickle function too. 

I'll post here if I find a workaround.

**Comment by Delgan** [comment]
Though, it's very curious that this only happens with Jupyter. Maybe it's worth asking one of the developers.

**Comment by hadim** [comment]
> Though, it's very curious that this only happens with Jupyter. Maybe it's worth asking one of the developers.

Yup, I feel like my prod scripts have the same issue but so far I haven't been able to reproduce it.

**Comment by ludaavics** [comment]
@hadim have you been able to discern what in jupyter makes this fail? (or to reproduce in your scripts?)

**Comment by hadim** [comment]
Not yet but if you find something please let me know.

**Comment by jmrichardson** [comment]
I'm having the same issue in scripts (not Jupyter).

**Comment by mhooreman** [comment]
Hello,

Please find below a simple example to reproduce is using standard environment (not jupyter).

Basically, the problem happens as soon as we add a file.

```python
import loguru
import joblib as jl

logger  = loguru.logger
logger.add('tmp.log')  # Problem doens't appears if we remove this line

def cb(x):
    logger.info("x = {}", x)

jl.Parallel(n_jobs=-1)(jl.delayed(cb)(x) for x in range(10))
```

**Comment by Delgan** [comment]
Hi @mhooreman. Thanks for the reproducible example.

Running your code on my computer, I got the following error:

```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/externals/loky/backend/queues.py", line 159, in _feed
    obj_ = dumps(obj, reducers=reducers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/externals/loky/backend/reduction.py", line 215, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/externals/loky/backend/reduction.py", line 208, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 931, in _file_reduce
    raise pickle.PicklingError(
_pickle.PicklingError: Cannot pickle files that are not opened for reading: a
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/delgan/Code/loguru/job.py", line 10, in <module>
    jl.Parallel(n_jobs=-1)(jl.delayed(cb)(x) for x in range(10))
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delgan/Code/loguru/env/lib/python3.12/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```

It appears `joblib` needs to pickle (i.e. serialize) the objects that will be used by the workers. Notably, it'll try to pickle the `cb()` function, and since `cb()` uses the `logger`, it will need to serialize it as well.

The interesting part of the error is here:

```
_pickle.PicklingError: Cannot pickle files that are not opened for reading: a
```

While adding a file-handler, Loguru will open the file in "append" mode by default. This is visibly incompatible with `joblib` (more precisely with `cloudpickle`). However, you can easily change the mode to `"a+"` (append and reading) by using the `mode` argument while adding the file-handler:

```python
import loguru
import joblib as jl

logger  = loguru.logger
logger.add('tmp.log', mode="a+")  # Problem doens't appears if we remove this line

def cb(x):
    logger.info("x = {}", x)

jl.Parallel(n_jobs=-1)(jl.delayed(cb)(x) for x in range(10))
```

The above code runs fine.

However, note that when using this solution, Loguru will not be able to synchronize concurrent writes on the file.  I'm not aware of `joblib` being able to neither. Therefore, depending on your OS, it might result in scrambled log lines for example.

That is why Loguru advises to use the `enqueue=True` argument which prevents concurrent write-accesses by using a messages queue internally. See [Compatibility with `multiprocessing` using `enqueue` argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument).
This does however requires the child processes to "inherit" the shared memory of the parent, which does not seem supported by `joblib` as far as I know.

---

Another workaround can be found in the `joblib`'s documentation: [Shared-memory semantics](https://joblib.readthedocs.io/en/latest/parallel.html#shared-memory-semantics).

The following code will also run fine:

```python
import loguru
import joblib as jl

logger  = loguru.logger
logger.add('tmp.log')  # Problem doens't appears if we remove this line

def cb(x):
    logger.info("x = {}", x)

jl.Parallel(n_jobs=-1, require='sharedmem')(jl.delayed(cb)(x) for x in range(10))
```

Maybe this is as safe as `enqueue=True`, I can't tell since I don't know `joblib` enough.

--- 

Finally, if one wants to protect concurrent writes without requiring shared memory, a specialized handler that implement inter-processes messaging must be used.

There  are a few examples in the documentation: [Sending and receiving log messages across network or processes](https://loguru.readthedocs.io/en/stable/resources/recipes.html#sending-and-receiving-log-messages-across-network-or-processes).

I plan to implement this mechanism as a built-in option for Loguru handlers in a future release. This should make it easier to use file-handlers with frameworks (such as `joblib` and `fastapi`) that do not support inheritance memory sharing.

**Comment by vinismarques** [comment]
Thanks @Delgan! I've hit this issue multiple times over the past few months, just spaced enough that I forgot how I handled it last time.

I remember having to move all worker methods to a new module to work around the issue in the past, but the `mode="a+"` seems to be the simplest as of now. I did notice I can't use `enqueue=True` with `mode="a+"`, but I'm not sure if it is really necessary on Linux either.
