### ISSUE TITLE
Should backtrace work in a console?

### ISSUE THREAD

**Issue by kmatt** [Delgan/loguru#5]
The backtrace output works in a Python script run via an interpreter, but not in a Python shell, instead printing less information. Is this expected?

```python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from loguru import logger
>>>
>>> logger.start("output.log", backtrace=True)  # Set 'False' to avoid leaking sensitive data in prod
1
>>>
>>> def func(a, b):
...     return a / b
...
>>> def nested(c):
...     try:
...         func(5, c)
...     except ZeroDivisionError:
...         logger.exception("What?!")
...
>>> nested(0)
2018-12-09 18:20:15.019 | ERROR    | __main__:nested:5 - What?!
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
> File "<stdin>", line 3, in nested
  File "<stdin>", line 2, in func

ZeroDivisionError: division by zero
>>>
```

**Comment by Delgan** [comment]
Ok, you caught me. I somehow _hacked_ the demo gif to display pretty stacktraces in the Python interactive shell. In reality, **it can't work**.

This is due to the fact that in the console, there is no file (see the `<stdin>`), so there is no way to know and show the line of code.
