### ISSUE TITLE
Logging with empty curly braces and args (or kwargs) raises an error

### ISSUE THREAD

**Issue by jelther** [Delgan/loguru#510]
Using curly braces and args (or kwargs) raises an exception when logging :
 
```
from loguru import logger
logger.info("test with empty curly braces {}",arg=1)

```

Exception:

```

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../lib/python3.8/site-packages/loguru/_logger.py", line 1971, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File ".../venv/lib/python3.8/site-packages/loguru/_logger.py", line 1948, in _log
    log_record["message"] = message.format(*args, **kwargs)
IndexError: Replacement index 0 out of range for positional args tuple

```

What is the alternative here to avoid this (or, at least, getting a more descriptive error) ?

**Comment by Delgan** [comment]
You can bypass string formatting by using `bind()` like this:

```python
logger.bind(arg=1).info("test with empt curly braces {}")
```

Alternatively, you can simply escape the braces:

```python
logger.info("test with empty curly braces {{}}", arg=1)
```
