### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by colinshin** [Delgan/loguru#511]
Traceback (most recent call last):
  File "/home/venv/lib/python3.8/site-packages/loguru/_handler.py", line 270, in _queued_writer
    message = queue.get()
  File "/usr/local/python3/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/usr/local/python3/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/python3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/python3/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
OSError: [Errno 9] Bad file descriptor
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: None

**Comment by Delgan** [comment]
Hi.

Does this error occur randomly or every time a message is logged?

**Comment by aryeko** [comment]
@Delgan I have such exception form some point until the process killed (due to Bad file descriptor I guess).
Attached the exceptions part from my log file [loguru exceptions.log](https://github.com/Delgan/loguru/files/7492058/loguru.exceptions.log)

I'm using the logger with the following configuration:
```python
from loguru import logger

logger.remove()
logger.add("hub.log",
            colorize=True, 
            format="<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level:<8}| {message}</level>", 
            level="DEBUG",
            rotation="50 MB", # Automatically rotate too big file
            enqueue=True) # Process/thread safe logging
```

Can I protect my app from loguru errors with the API ay adding a global exception handler or something similar?

Thanks!

**Comment by xiaohange** [comment]
The version I use is' 0.6.0 '. The following error will be prompted after the deployment of Linux docker. How to solve this problem?

```
--- Logging error in Loguru Handler #3 ---
Record was: None
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/loguru/_handler.py", line 272, in _queued_writer
    message = queue.get()
  File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 366, in get
    res = self._reader.recv_bytes()
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
OSError: [Errno 9] Bad file descriptor
--- End of logging error ---
```

**Comment by middlestone** [comment]
I have the same problem in version "0.7.2"

**Comment by darwin403** [comment]
I have the same problem. The only change for break was running my code on an arm64 server instead of amd64. Thought this might help for future debugging.

**Comment by Delgan** [comment]
@middlestone Can you provide more info please, such as how often it occurs and whether a particular action triggers the error?

A fully reproducible example would be of great help. Right now, I can't say if it's a bug within Loguru or not.

**Comment by LwithD** [comment]
I got same problem in version "0.7.0"
here's the log:
```python
--- Logging error in Loguru Handler #2 ---
Record was: {'elapsed': datetime.timedelta(seconds=87, microseconds=531510), 'exception': None, 'extra': {}, 'file': (name='main.py', path='/mnt/Model/main.py'), 'function': 'process', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 74, 'message': 'processing file_path:/mnt/test_data/video/1696064134.h264  kwargs:{}', 'module': 'main', 'name': 'main', 'process': (id=13, name='MainProcess'), 'thread': (id=140116484359936, name='AnyIO worker thread'), 'time': datetime(2024, 4, 29, 11, 48, 10, 748173, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.8/site-packages/loguru/_handler.py", line 197, in emit
    self._sink.write(str_record)
  File "/usr/local/python/lib/python3.8/site-packages/loguru/_file_sink.py", line 206, in write
    if self._rotation_function is not None and self._rotation_function(message, self._file):
  File "/usr/local/python/lib/python3.8/site-packages/loguru/_file_sink.py", line 105, in rotation_size
    file.seek(0, 2)
OSError: [Errno 9] Bad file descriptor
--- End of logging error ---```

I add two handles and one of them is like this:
```python
logger.add(
            sink=f"{self.message.log_dir}/{log_file_template}",  
            level="DEBUG",
            rotation="1000 MB", 
            compression="zip",  
            # serialize=True, 
            backtrace=True,
            diagnose=True,  
            filter=lambda x: x["extra"].get("name", None) != "syslog",
        )
```
and another one 
```python
logger.add(
    sink=f"{log_folder}/{log_file_template}",  
    level=log_level,
    rotation="100 MB", 
    compression="zip", 
    # serialize=True, 
    backtrace=True,
    diagnose=True,  
    filter=lambda x: x["extra"].get("name", None) == "sys_log",
)
```
the code is running in docker

sry for my pool english grammar
