### ISSUE TITLE
Errors when importing a library that also uses Loguru

### ISSUE THREAD

**Issue by kace** [Delgan/loguru#534]
Hi Delgan,

I've run into issues integrating with another lib that recently moved their logging to Loguru from the stdlib. For reference I'm referring to the [napalm](https://github.com/napalm-automation/napalm) dependency [ciscoconfparse](https://github.com/mpenning/ciscoconfparse). I've linked their commits below for tag v1.5.48 for you reference.

Anyways, the ciscoconfparse dev's seem to configure the Loguru logger quite a bit - they remove all of the handlers and add their own. This results in errors on my side.  First they are `BlockIOError`'s then if I let it go a a bit longer also include `OSError`'s - see below.

I know that you probably can't help me too much since it's another lib causing me problems, but I was curious if you could offer me some advice on how to handle conflicting Loguru logger config given that there is only one global logger?

Thanks!

```
--- Logging error in Loguru Handler #2 ---
Traceback (most recent call last):
  File "/home/<user>/.local/share/virtualenvs/test_deps-m_cu5jxE/lib/python3.8/site-packages/loguru/_handler.py", line 270, in _queued_writer
    message = queue.get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
BlockingIOError: [Errno 11] Resource temporarily unavailable
--- End of logging error ---
```

```
--- Logging error in Loguru Handler #2 ---
Record was: None
    self._send(header + buf)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
Traceback (most recent call last):
  File "/home/ksiman/.local/share/virtualenvs/test_deps-m_cu5jxE/lib/python3.8/site-packages/loguru/_handler.py", line 270, in _queued_writer
    message = queue.get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
    n = write(self._handle, buf)
BlockingIOError: [Errno 11] Resource temporarily unavailable
OSError: [Errno 9] Bad file descriptor
--- End of logging error ---
```

Relevant ciscoconfparse commits

- https://github.com/mpenning/ciscoconfparse/commit/72dcc02d164be22c8c0f4d8aa454dec89a67af18
- https://github.com/mpenning/ciscoconfparse/commit/0612d33ec82e1a154e9ebd4a3eb708a2ca371c95

**Comment by mpenning** [comment]
Speaking only for [ciscoconfparse](https://github.com/mpenning/ciscoconfparse "ciscoconfparse"), this problem has been sufficiently addressed by the following commit:

- https://github.com/mpenning/ciscoconfparse/commit/dd0bd46d31df9d56d6636ca1c38e1d6159c9fea3

See [ciscoconfparse issue #211](https://github.com/mpenning/ciscoconfparse/issues/211) for usage details.

I suspect we can close this loguru ticket, but I'll let @kace confirm...

**Comment by kace** [comment]
Thanks @mpenning!

I still would like to follow up on this topic with regards to Loguru though. It would be great if I didn't have to ask library developers who also use Loguru for a method to disable their logger.
