### ISSUE TITLE
Testing: python 3.10 formats changed line numbers.

### ISSUE THREAD

**Issue by bnavigator** [Delgan/loguru#550]
The following tests fail with Python 3.10:

```
[   40s] =================================== FAILURES ===================================
[   40s] ________ test_exception_others[handler_formatting_with_context_manager] ________
[   40s] 
[   40s] filename = 'handler_formatting_with_context_manager'
[   40s] 
[   40s]     @pytest.mark.parametrize(
[   40s]         "filename",
[   40s]         [
[   40s]             "assertionerror_without_traceback",
[   40s]             "catch_as_context_manager",
[   40s]             "catch_as_decorator_with_parentheses",
[   40s]             "catch_as_decorator_without_parentheses",
[   40s]             "catch_as_function",
[   40s]             "catch_message",
[   40s]             "exception_formatting_coroutine",
[   40s]             "exception_formatting_function",
[   40s]             "exception_formatting_generator",
[   40s]             "exception_in_property",
[   40s]             "handler_formatting_with_context_manager",
[   40s]             "handler_formatting_with_decorator",
[   40s]             "level_name",
[   40s]             "level_number",
[   40s]             "message_formatting_with_context_manager",
[   40s]             "message_formatting_with_decorator",
[   40s]             "nested_with_reraise",
[   40s]             "syntaxerror_without_traceback",
[   40s]             "sys_tracebacklimit",
[   40s]             "sys_tracebacklimit_negative",
[   40s]             "sys_tracebacklimit_none",
[   40s]             "sys_tracebacklimit_unset",
[   40s]             "zerodivisionerror_without_traceback",
[   40s]         ],
[   40s]     )
[   40s]     def test_exception_others(filename):
[   40s] >       compare_exception("others", filename)
[   40s] 
[   40s] tests/test_exceptions_formatting.py:216: 
[   40s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   40s] 
[   40s] dirname = 'others', filename = 'handler_formatting_with_context_manager'
[   40s] 
[   40s]     def compare_exception(dirname, filename):
[   40s]         cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
[   40s]         python = sys.executable or "python"
[   40s]         filepath = os.path.join("tests", "exceptions", "source", dirname, filename + ".py")
[   40s]         outpath = os.path.join(cwd, "tests", "exceptions", "output", dirname, filename + ".txt")
[   40s]     
[   40s]         with subprocess.Popen(
[   40s]             [python, filepath],
[   40s]             shell=False,
[   40s]             cwd=cwd,
[   40s]             stdout=subprocess.PIPE,
[   40s]             stderr=subprocess.PIPE,
[   40s]             universal_newlines=True,
[   40s]             env=dict(os.environ, PYTHONPATH=cwd, PYTHONIOENCODING="utf8"),
[   40s]         ) as proc:
[   40s]             stdout, stderr = proc.communicate()
[   40s]             print(stderr, file=sys.stderr)
[   40s]             assert proc.returncode == 0
[   40s]             assert stdout == ""
[   40s]             assert stderr != ""
[   40s]     
[   40s]         stderr = normalize(stderr)
[   40s]     
[   40s]         # generate(stderr, outpath)
[   40s]     
[   40s]         with open(outpath, "r") as file:
[   40s] >           assert stderr == file.read()
[   40s] E           assert ('__main__ handler_formatting_with_context_manager.py a 16\n'\n 'Traceback (most recent call last):\n'\n '  File '\n '"tests/exceptions/source/others/handler_formatting_with_context_manager.py", '\n 'line 17, in a\n'\n '    1 / 0\n'\n 'ZeroDivisionError: division by zero\n') == ('__main__ handler_formatting_with_context_manager.py a 17\n'\n 'Traceback (most recent call last):\n'\n '  File '\n '"tests/exceptions/source/others/handler_formatting_with_context_manager.py", '\n 'line 17, in a\n'\n '    1 / 0\n'\n 'ZeroDivisionError: division by zero\n')
[   40s] E             - __main__ handler_formatting_with_context_manager.py a 17
[   40s] E             ?                                                        ^
[   40s] E             + __main__ handler_formatting_with_context_manager.py a 16
[   40s] E             ?                                                        ^
[   40s] E               Traceback (most recent call last):
[   40s] E                 File "tests/exceptions/source/others/handler_formatting_with_context_manager.py", line 17, in a
[   40s] E                   1 / 0
[   40s] E               ZeroDivisionError: division by zero
[   40s] 
[   40s] tests/test_exceptions_formatting.py:104: AssertionError
[   40s] ----------------------------- Captured stderr call -----------------------------
[   40s] __main__ handler_formatting_with_context_manager.py a 16
[   40s] Traceback (most recent call last):
[   40s]   File "/home/abuild/rpmbuild/BUILD/loguru-0.5.3/tests/exceptions/source/others/handler_formatting_with_context_manager.py", line 17, in a
[   40s]     1 / 0
[   40s] ZeroDivisionError: division by zero
[   40s] 
[   40s] ________ test_exception_others[message_formatting_with_context_manager] ________
[   40s] 
[   40s] filename = 'message_formatting_with_context_manager'
[   40s] 
[   40s]     @pytest.mark.parametrize(
[   40s]         "filename",
[   40s]         [
[   40s]             "assertionerror_without_traceback",
[   40s]             "catch_as_context_manager",
[   40s]             "catch_as_decorator_with_parentheses",
[   40s]             "catch_as_decorator_without_parentheses",
[   40s]             "catch_as_function",
[   40s]             "catch_message",
[   40s]             "exception_formatting_coroutine",
[   40s]             "exception_formatting_function",
[   40s]             "exception_formatting_generator",
[   40s]             "exception_in_property",
[   40s]             "handler_formatting_with_context_manager",
[   40s]             "handler_formatting_with_decorator",
[   40s]             "level_name",
[   40s]             "level_number",
[   40s]             "message_formatting_with_context_manager",
[   40s]             "message_formatting_with_decorator",
[   40s]             "nested_with_reraise",
[   40s]             "syntaxerror_without_traceback",
[   40s]             "sys_tracebacklimit",
[   40s]             "sys_tracebacklimit_negative",
[   40s]             "sys_tracebacklimit_none",
[   40s]             "sys_tracebacklimit_unset",
[   40s]             "zerodivisionerror_without_traceback",
[   40s]         ],
[   40s]     )
[   40s]     def test_exception_others(filename):
[   40s] >       compare_exception("others", filename)
[   40s] 
[   40s] tests/test_exceptions_formatting.py:216: 
[   40s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   40s] 
[   40s] dirname = 'others', filename = 'message_formatting_with_context_manager'
[   40s] 
[   40s]     def compare_exception(dirname, filename):
[   40s]         cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
[   40s]         python = sys.executable or "python"
[   40s]         filepath = os.path.join("tests", "exceptions", "source", dirname, filename + ".py")
[   40s]         outpath = os.path.join(cwd, "tests", "exceptions", "output", dirname, filename + ".txt")
[   40s]     
[   40s]         with subprocess.Popen(
[   40s]             [python, filepath],
[   40s]             shell=False,
[   40s]             cwd=cwd,
[   40s]             stdout=subprocess.PIPE,
[   40s]             stderr=subprocess.PIPE,
[   40s]             universal_newlines=True,
[   40s]             env=dict(os.environ, PYTHONPATH=cwd, PYTHONIOENCODING="utf8"),
[   40s]         ) as proc:
[   40s]             stdout, stderr = proc.communicate()
[   40s]             print(stderr, file=sys.stderr)
[   40s]             assert proc.returncode == 0
[   40s]             assert stdout == ""
[   40s]             assert stderr != ""
[   40s]     
[   40s]         stderr = normalize(stderr)
[   40s]     
[   40s]         # generate(stderr, outpath)
[   40s]     
[   40s]         with open(outpath, "r") as file:
[   40s] >           assert stderr == file.read()
[   40s] E           assert ('__main__ message_formatting_with_context_manager.py a 10\n'\n 'Traceback (most recent call last):\n'\n '  File '\n '"tests/exceptions/source/others/message_formatting_with_context_manager.py", '\n 'line 13, in a\n'\n '    1 / 0\n'\n 'ZeroDivisionError: division by zero\n') == ('__main__ message_formatting_with_context_manager.py a 13\n'\n 'Traceback (most recent call last):\n'\n '  File '\n '"tests/exceptions/source/others/message_formatting_with_context_manager.py", '\n 'line 13, in a\n'\n '    1 / 0\n'\n 'ZeroDivisionError: division by zero\n')
[   40s] E             - __main__ message_formatting_with_context_manager.py a 13
[   40s] E             ?                                                        ^
[   40s] E             + __main__ message_formatting_with_context_manager.py a 10
[   40s] E             ?                                                        ^
[   40s] E               Traceback (most recent call last):
[   40s] E                 File "tests/exceptions/source/others/message_formatting_with_context_manager.py", line 13, in a
[   40s] E                   1 / 0
[   40s] E               ZeroDivisionError: division by zero
[   40s] 
[   40s] tests/test_exceptions_formatting.py:104: AssertionError
[   40s] ----------------------------- Captured stderr call -----------------------------
[   40s] __main__ message_formatting_with_context_manager.py a 10
[   40s] Traceback (most recent call last):
[   40s]   File "/home/abuild/rpmbuild/BUILD/loguru-0.5.3/tests/exceptions/source/others/message_formatting_with_context_manager.py", line 13, in a
[   40s]     1 / 0
[   40s] ZeroDivisionError: division by zero
[   40s] 

...
[   40s] =========================== short test summary info ============================
[   40s] FAILED tests/test_exceptions_formatting.py::test_exception_others[handler_formatting_with_context_manager]
[   40s] FAILED tests/test_exceptions_formatting.py::test_exception_others[message_formatting_with_context_manager]
```

**Comment by Delgan** [comment]
Thanks for letting me know!

I do indeed need to make some updates in the code and CI, I will take care of it as soon as possible.

**Comment by fabaff** [comment]
Can be reproduced with Python 3.10.1

```bash
============================= test session starts ==============================
platform linux -- Python 3.10.1, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /build/loguru-0.5.3
collected 1359 items / 13 deselected / 1346 selected                           

tests/test_activation.py ..............................                  [  2%]
[...]
tests/test_exceptions_formatting.py .................................... [ 47%]
...........................F...F........                                 [ 50%]
tests/test_filesink_compression.py ..................................... [ 53%]
.................                                                        [ 54%]
tests/test_filesink_delay.py ..........                                  [ 55%]
tests/test_filesink_retention.py ....................................... [ 58%]
..........                                                               [ 59%]
tests/test_filesink_rotation.py ........................................ [ 62%]
...........................................                              [ 65%]
tests/test_formatting.py ............................................... [ 68%]
................................                                         [ 71%]
tests/test_get_frame.py ...                                              [ 71%]
tests/test_interception.py ............                                  [ 72%]
tests/test_levels.py .......................................             [ 75%]
tests/test_multiprocessing.py ...............................            [ 77%]
tests/test_opt.py ...................................................... [ 81%]
........................................................................ [ 86%]
........................                                                 [ 88%]
tests/test_parse.py .........................                            [ 90%]
tests/test_patch.py .......                                              [ 91%]
tests/test_pickling.py ................................................. [ 94%]
....                                                                     [ 95%]
tests/test_propagation.py ......                                         [ 95%]
tests/test_recattr.py .........                                          [ 96%]
tests/test_remove.py ...........                                         [ 96%]
tests/test_repr.py ....................                                  [ 98%]
tests/test_standard_handler.py ................                          [ 99%]
tests/test_threading.py .....                                            [100%]

=================================== FAILURES ===================================
________ test_exception_others[handler_formatting_with_context_manager] ________

filename = 'handler_formatting_with_context_manager'

    @pytest.mark.parametrize(
        "filename",
        [
            "assertionerror_without_traceback",
            "catch_as_context_manager",
            "catch_as_decorator_with_parentheses",
            "catch_as_decorator_without_parentheses",
            "catch_as_function",
            "catch_message",
            "exception_formatting_coroutine",
            "exception_formatting_function",
            "exception_formatting_generator",
            "exception_in_property",
            "handler_formatting_with_context_manager",
            "handler_formatting_with_decorator",
            "level_name",
            "level_number",
            "message_formatting_with_context_manager",
            "message_formatting_with_decorator",
            "nested_with_reraise",
            "syntaxerror_without_traceback",
            "sys_tracebacklimit",
            "sys_tracebacklimit_negative",
            "sys_tracebacklimit_none",
            "sys_tracebacklimit_unset",
            "zerodivisionerror_without_traceback",
        ],
    )
    def test_exception_others(filename):
>       compare_exception("others", filename)

tests/test_exceptions_formatting.py:216: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dirname = 'others', filename = 'handler_formatting_with_context_manager'

    def compare_exception(dirname, filename):
        cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        python = sys.executable or "python"
        filepath = os.path.join("tests", "exceptions", "source", dirname, filename + ".py")
        outpath = os.path.join(cwd, "tests", "exceptions", "output", dirname, filename + ".txt")
    
        with subprocess.Popen(
            [python, filepath],
            shell=False,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            env=dict(os.environ, PYTHONPATH=cwd, PYTHONIOENCODING="utf8"),
        ) as proc:
            stdout, stderr = proc.communicate()
            print(stderr, file=sys.stderr)
            assert proc.returncode == 0
            assert stdout == ""
            assert stderr != ""
    
        stderr = normalize(stderr)
    
        # generate(stderr, outpath)
    
        with open(outpath, "r") as file:
>           assert stderr == file.read()
E           AssertionError: assert '__main__ han...ion by zero\n' == '__main__ han...ion by zero\n'
E             Skipping 45 identical leading characters in diff, use -v to show
E             Skipping 171 identical trailing characters in diff, use -v to show
E             - ger.py a 17
E             ?           ^
E             + ger.py a 16
E             ?           ^
E               Tracebac

tests/test_exceptions_formatting.py:104: AssertionError
----------------------------- Captured stderr call -----------------------------
__main__ handler_formatting_with_context_manager.py a 16
Traceback (most recent call last):
  File "/build/loguru-0.5.3/tests/exceptions/source/others/handler_formatting_with_context_manager.py", line 17, in a
    1 / 0
ZeroDivisionError: division by zero

________ test_exception_others[message_formatting_with_context_manager] ________

filename = 'message_formatting_with_context_manager'

    @pytest.mark.parametrize(
        "filename",
        [
            "assertionerror_without_traceback",
            "catch_as_context_manager",
            "catch_as_decorator_with_parentheses",
            "catch_as_decorator_without_parentheses",
            "catch_as_function",
            "catch_message",
            "exception_formatting_coroutine",
            "exception_formatting_function",
            "exception_formatting_generator",
            "exception_in_property",
            "handler_formatting_with_context_manager",
            "handler_formatting_with_decorator",
            "level_name",
            "level_number",
            "message_formatting_with_context_manager",
            "message_formatting_with_decorator",
            "nested_with_reraise",
            "syntaxerror_without_traceback",
            "sys_tracebacklimit",
            "sys_tracebacklimit_negative",
            "sys_tracebacklimit_none",
            "sys_tracebacklimit_unset",
            "zerodivisionerror_without_traceback",
        ],
    )
    def test_exception_others(filename):
>       compare_exception("others", filename)

tests/test_exceptions_formatting.py:216: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

dirname = 'others', filename = 'message_formatting_with_context_manager'

    def compare_exception(dirname, filename):
        cwd = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
        python = sys.executable or "python"
        filepath = os.path.join("tests", "exceptions", "source", dirname, filename + ".py")
        outpath = os.path.join(cwd, "tests", "exceptions", "output", dirname, filename + ".txt")
    
        with subprocess.Popen(
            [python, filepath],
            shell=False,
            cwd=cwd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            env=dict(os.environ, PYTHONPATH=cwd, PYTHONIOENCODING="utf8"),
        ) as proc:
            stdout, stderr = proc.communicate()
            print(stderr, file=sys.stderr)
            assert proc.returncode == 0
            assert stdout == ""
            assert stderr != ""
    
        stderr = normalize(stderr)
    
        # generate(stderr, outpath)
    
        with open(outpath, "r") as file:
>           assert stderr == file.read()
E           AssertionError: assert '__main__ mes...ion by zero\n' == '__main__ mes...ion by zero\n'
E             Skipping 45 identical leading characters in diff, use -v to show
E             Skipping 171 identical trailing characters in diff, use -v to show
E             - ger.py a 13
E             ?           ^
E             + ger.py a 10
E             ?           ^
E               Tracebac

tests/test_exceptions_formatting.py:104: AssertionError
----------------------------- Captured stderr call -----------------------------
__main__ message_formatting_with_context_manager.py a 10
Traceback (most recent call last):
  File "/build/loguru-0.5.3/tests/exceptions/source/others/message_formatting_with_context_manager.py", line 13, in a
    1 / 0
ZeroDivisionError: division by zero

=============================== warnings summary ===============================
tests/test_add_option_catch.py::test_broken_sink_not_caught_enqueue
  /nix/store/chwjpc7aq97ihs7isn966dwcw5qzn6ah-python3.10-pytest-6.2.5/lib/python3.10/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread loguru-writer-0
  
  Traceback (most recent call last):
    File "/nix/store/b798fp24zf2fdafmyyc4sxfr48ly5yy9-python3-3.10.1/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
      self.run()
    File "/nix/store/b798fp24zf2fdafmyyc4sxfr48ly5yy9-python3-3.10.1/lib/python3.10/threading.py", line 946, in run
      self._target(*self._args, **self._kwargs)
    File "/build/loguru-0.5.3/loguru/_handler.py", line 287, in _queued_writer
      self._sink.write(message)
    File "/build/loguru-0.5.3/loguru/_simple_sinks.py", line 119, in write
      self._function(message)
    File "/build/loguru-0.5.3/tests/test_add_option_catch.py", line 131, in broken_sink
      raise ValueError("Nop")
  ValueError: Nop
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests/test_exceptions_formatting.py::test_exception_others[handler_formatting_with_context_manager]
FAILED tests/test_exceptions_formatting.py::test_exception_others[message_formatting_with_context_manager]
````

**Comment by Delgan** [comment]
Fixed on `master` branch. :+1:

Python 3.10 changed the `frame.f_lineno` value when `__exit__` function of context manager is called:
* https://bugs.python.org/issue42246
* https://bugs.python.org/issue43933
