### ISSUE TITLE
`super()`: `TypeError: super() argument 1 must be type, not function`

### ISSUE THREAD

**Issue by mpenning** [Delgan/loguru#621]
`super()` throws an error:
```python
% python foo.py
2022-03-21 13:35:10.211 | ERROR    | __main__:<module>:45 - An error has been caught in function '<module>', process 'MainProcess' (56772), thread 'MainThread' (4565976576):
Traceback (most recent call last):

> File "/Users/mpenning/fixme/ansible_venv_lab/foo.py", line 45, in <module>
    thislist = AnsibleHostList()
               └ <function AnsibleHostList at 0x108c8edc0>

  File "/Users/mpenning/fixme/ansible_venv_lab/foo.py", line 13, in __init__
    super(AnsibleHostList, self).__init__()
          │                └ <unprintable AnsibleHostList object>
          └ <function AnsibleHostList at 0x108c8edc0>

TypeError: super() argument 1 must be type, not function
```

```python
from collections.abc import MutableSequence
import sys

from loguru import logger

@logger.catch(default=True, onerror=lambda _: sys.exit(1))
class AnsibleHostList(MutableSequence):
    """A container for manipulating lists of hosts"""

    def __init__(self, data=None):
        """Initialize the class"""
        super(AnsibleHostList, self).__init__()
        if (data is not None):
            self._list = list(data)
        else:
            self._list = list()

    def __repr__(self):
        return "<{0} {1}>".format(self.__class__.__name__, self.list)

    def __len__(self):
        """List length"""
        return len(self._list)

    def __getitem__(self, ii):
        """Get a list item"""
        return self._list[ii]

    def __delitem__(self, ii):
        """Delete an item"""
        del self._list[ii]

    def __setitem__(self, ii, val):
        # optional: self._acl_check(val)
        self._list[ii] = val

    def __str__(self):
        return str(self._list)

    def insert(self, ii, val):
        # optional: self._acl_check(val)
        self._list.insert(ii, val)

    def append(self, val):
        self.insert(len(self._list), val)

thislist = AnsibleHostList()
print(thislist)
```

However, if I remove `@logger.catch(default=True, onerror=lambda _: sys.exit(1))`, the class can use `super()` as required.

I can work around this problem by adding `@logger.catch(...)` to every method on the function, but that's an awful workaround for this problem.

I believe the behavior above should be a bug...  Please advise on the next steps to fix this... I can try to submit a PR, if-required... but I don't know this code-base very well...

I'm running python 3.9.10 with loguru v0.6.0 on macOS Catalina

**Comment by Delgan** [comment]
Hi.

The `logger.catch()` is not really meant to decorate classes, its primary use is for functions.
