### ISSUE TITLE
websocket error on windows.

### ISSUE THREAD

**Issue by derac** [Delgan/loguru#632]
```
PS F:\Projects\reddit-place-script-2022> poetry run python .\main.py
Traceback (most recent call last):
  File ".\main.py", line 10, in <module>
    from websocket import create_connection
ImportError: cannot import name 'create_connection' from 'websocket' (C:\Users\Derek\AppData\Local\pypoetry\Cache\virtualenvs\reddit-place-script-2022-3Z_8heeH-py3.8\lib\site-packages\websocket\__init__.py)
```
before this I was getting
```
PS F:\Projects\reddit-place-script-2022> poetry run python .\main.py
Traceback (most recent call last):
  File "./main.py", line 10, in <module>
    from websocket import create_connection
ModuleNotFoundError: No module named 'websocket'
```
I added Websocket to the poetry config, though. It's in a PR.

**Comment by derac** [comment]
pip worked 🤷🏻‍♂️

**Comment by Delgan** [comment]
Is it related to Loguru? Can you share a reproducible example please?

**Comment by derac** [comment]
Um woops, wrong project. sorry!
