### ISSUE TITLE
log.add creates a batch of log files but cannot write into files

### ISSUE THREAD

**Issue by KafCoppelia** [Delgan/loguru#648]
Here is an example. When the element in list `self._chips_list[i] == 1`, add a logger with a specific log file. The method `record` is to record something to a specific log file. Generally I was used `logger.info` in an `async function` such as `main` as below. 
The log was printed to console as expected but was not recorded in file. I don't know hot to fix it☹
```
from loguru import logger
from pathlib import Path
import asyncio

async def main():
    manager = LogManager()
    msg = "hello world"
    manager.record(2, msg)

class LogManager:
    def __init__(self):
        self._chips_list = [1, 0, 1, 0, 0]
        self._logger_id = []
        
        for index in range(0, len(self._chips_list)):
            if self._chips_list[index] == 1:
                log_path = Path.cwd() / (str(index) +  ".log")
                lid = logger.add(log_path, enqueue=True, filter=lambda record: record["extra"]["chip"] == str(index))
                self._logger_id.append(lid)
            else:
                self._logger_id.append(0)
    
    def record(self, index: int, msg: str):
        logger.bind(chip=str(index)).info(f"{index} | {msg}")

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

**Comment by KafCoppelia** [comment]
In my case, I just found if I import a `class` which logger is included from `B.py` to `A.py`, such as recording the received data from UART, and in `A.py` there is another class in which I use the logger from `B.py`. Then I run `A.py`, the log will print on console but won't record in files even tho' the file path in `logger.add(...)` is correct.

Then I change my code. In `A.py`, I use loguru in the `class` I mentioned above,  the log can print and record normally. Is the `logger` object cannnot be `import` to another `.py`? Or will cause not writing into files?

Plus, I use `filter`, `logger.bind(..).info(...)`, and `logger.complete()` in `async def` in my case🤔

**Comment by KafCoppelia** [comment]
I now got the crux of the above questions. For example, When I use `for` to create a batch of logs with regular names, loguru can create log files OK, but I cannot write into files using `logger.bind(...).info(...)`. Log files are empty.
```
from loguru import logger
logger.remove()

for i in range(0, 8):
    logger.add(f"{i}.log", filter=lambda record: record["extra"]["chip"] == i)
   
# logger.add("1.log", filter=lambda record: record["extra"]["chip"] == 1)
# logger.add("2.log", filter=lambda record: record["extra"]["chip"] == 2) 
# logger.add("3.log", filter=lambda record: record["extra"]["chip"] == 3)
# logger.add("4.log", filter=lambda record: record["extra"]["chip"] == 4) 
# logger.add("5.log", filter=lambda record: record["extra"]["chip"] == 5)
# logger.add("6.log", filter=lambda record: record["extra"]["chip"] == 6)

logger.bind(chip=2).error("Error chip #2")    
logger.bind(chip=5).info("Hello chip #5")
```
Then, if I `logger.add(...)``` obviously enough, loguru can create and write into log files.
```
from loguru import logger
logger.remove()

# for i in range(0, 8):
#     logger.add(f"{i}.log", filter=lambda record: record["extra"]["chip"] == i)
   
logger.add("1.log", filter=lambda record: record["extra"]["chip"] == 1)
logger.add("2.log", filter=lambda record: record["extra"]["chip"] == 2) 
logger.add("3.log", filter=lambda record: record["extra"]["chip"] == 3)
logger.add("4.log", filter=lambda record: record["extra"]["chip"] == 4) 
logger.add("5.log", filter=lambda record: record["extra"]["chip"] == 5)
logger.add("6.log", filter=lambda record: record["extra"]["chip"] == 6)

logger.bind(chip=2).error("Error chip #2")    
logger.bind(chip=5).info("Hello chip #5")
```
Windows, Python 3.9.10

**Comment by Delgan** [comment]
Hi @KafCoppelia.

Your hitting a classical pitfall of Python, see [Why do lambdas defined in a loop with different values all return the same result?](https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result).

Try the following:

```python
for i in range(0, 8):
    logger.add(f"{i}.log", filter=lambda record, i=i: record["extra"]["chip"] == i)
```

**Comment by KafCoppelia** [comment]
Wow thanks a lot! This is truly a classic pitfall about lambda function!
As you can see, I will create a batch of logs to write, and then I'd like to `logger.add(sys.stderr)`, logging on my console. 
If so, when I use `logger.info(..)` instead of the limit of `logger.bind(...).info(...)`, the loguru will raise `logging error`.

**Comment by Delgan** [comment]
@KafCoppelia Which error exactly? Can you share the message so I can understand it please?

**Comment by KafCoppelia** [comment]
Here is the simplifiede scenario:
```
from loguru import logger
import sys
li = []
logger.remove()
logger.add(sys.stderr)

li.append(logger.add("1.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 1))
li.append(logger.add("2.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 2))
li.append(logger.add("3.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 3))
li.append(logger.add("4.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 4))
li.append(logger.add("5.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 5))
li.append(logger.add("6.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 6))

logger.bind(chip=5).info("Hello chip #5")
logger.bind(chip=2).error("Error chip #2")

logger.info("System info blahblahblah")
```
Then due to I don't use `.bind(...)` so:
```
2022-05-04 19:46:30.958 | INFO     | __main__:<module>:17 - Hello chip #5
2022-05-04 19:46:30.982 | ERROR    | __main__:<module>:18 - Error chip #2
2022-05-04 19:46:30.985 | INFO     | __main__:<module>:20 - System info blahblahblah
--- Logging error in Loguru Handler #2 ---
Record was: {'elapsed': datetime.timedelta(microseconds=162851), 'exception': None, 'extra': {}, 'file': (name='t.py', path='d:\\WORK\\JXR151T_VERIFY_BOARD\\VerifyConsoleJXR151T_V020\\t.py'), 'function': '<module>', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 20, 'message': 'System info blahblahblah', 'module': 't', 'name': '__main__', 'process': (id=544, name='MainProcess'), 'thread': (
id=22864, name='MainThread'), 'time': datetime(2022, 5, 4, 19, 46, 30, 985198, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\miniconda3\envs\jxr151t\lib\site-packages\loguru\_handler.py", line 104, in emit
    if not self._filter(record):
  File "d:\WORK\JXR151T_VERIFY_BOARD\VerifyConsoleJXR151T_V020\t.py", line 10, in <lambda>
    li.append(logger.add("1.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 1))
KeyError: 'chip'
--- End of logging error ---
--- Logging error in Loguru Handler #3 ---
Record was: {'elapsed': datetime.timedelta(microseconds=162851), 'exception': None, 'extra': {}, 'file': (name='t.py', path='d:\\WORK\\JXR151T_VERIFY_BOARD\\VerifyConsoleJXR151T_V020\\t.py'), 'function': '<module>', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 20, 'message': 'System info blahblahblah', 'module': 't', 'name': '__main__', 'process': (id=544, name='MainProcess'), 'thread': (
id=22864, name='MainThread'), 'time': datetime(2022, 5, 4, 19, 46, 30, 985198, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\miniconda3\envs\jxr151t\lib\site-packages\loguru\_handler.py", line 104, in emit
    if not self._filter(record):
  File "d:\WORK\JXR151T_VERIFY_BOARD\VerifyConsoleJXR151T_V020\t.py", line 11, in <lambda>
    li.append(logger.add("2.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 2))
KeyError: 'chip'
--- End of logging error ---
--- Logging error in Loguru Handler #4 ---
Record was: {'elapsed': datetime.timedelta(microseconds=162851), 'exception': None, 'extra': {}, 'file': (name='t.py', path='d:\\WORK\\JXR151T_VERIFY_BOARD\\VerifyConsoleJXR151T_V020\\t.py'), 'function': '<module>', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 20, 'message': 'System info blahblahblah', 'module': 't', 'name': '__main__', 'process': (id=544, name='MainProcess'), 'thread': (
id=22864, name='MainThread'), 'time': datetime(2022, 5, 4, 19, 46, 30, 985198, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\miniconda3\envs\jxr151t\lib\site-packages\loguru\_handler.py", line 104, in emit
    if not self._filter(record):
  File "d:\WORK\JXR151T_VERIFY_BOARD\VerifyConsoleJXR151T_V020\t.py", line 12, in <lambda>
    li.append(logger.add("3.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 3))
KeyError: 'chip'
--- End of logging error ---
--- Logging error in Loguru Handler #5 ---
Record was: {'elapsed': datetime.timedelta(microseconds=162851), 'exception': None, 'extra': {}, 'file': (name='t.py', path='d:\\WORK\\JXR151T_VERIFY_BOARD\\VerifyConsoleJXR151T_V020\\t.py'), 'function': '<module>', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 20, 'message': 'System info blahblahblah', 'module': 't', 'name': '__main__', 'process': (id=544, name='MainProcess'), 'thread': (
id=22864, name='MainThread'), 'time': datetime(2022, 5, 4, 19, 46, 30, 985198, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\miniconda3\envs\jxr151t\lib\site-packages\loguru\_handler.py", line 104, in emit
    if not self._filter(record):
  File "d:\WORK\JXR151T_VERIFY_BOARD\VerifyConsoleJXR151T_V020\t.py", line 13, in <lambda>
    li.append(logger.add("4.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 4))
KeyError: 'chip'
--- End of logging error ---
--- Logging error in Loguru Handler #6 ---
Record was: {'elapsed': datetime.timedelta(microseconds=162851), 'exception': None, 'extra': {}, 'file': (name='t.py', path='d:\\WORK\\JXR151T_VERIFY_BOARD\\VerifyConsoleJXR151T_V020\\t.py'), 'function': '<module>', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 20, 'message': 'System info blahblahblah', 'module': 't', 'name': '__main__', 'process': (id=544, name='MainProcess'), 'thread': (
id=22864, name='MainThread'), 'time': datetime(2022, 5, 4, 19, 46, 30, 985198, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\miniconda3\envs\jxr151t\lib\site-packages\loguru\_handler.py", line 104, in emit
    if not self._filter(record):
  File "d:\WORK\JXR151T_VERIFY_BOARD\VerifyConsoleJXR151T_V020\t.py", line 14, in <lambda>
    li.append(logger.add("5.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 5))
KeyError: 'chip'
--- End of logging error ---
--- Logging error in Loguru Handler #7 ---
Record was: {'elapsed': datetime.timedelta(microseconds=162851), 'exception': None, 'extra': {}, 'file': (name='t.py', path='d:\\WORK\\JXR151T_VERIFY_BOARD\\VerifyConsoleJXR151T_V020\\t.py'), 'function': '<module>', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 20, 'message': 'System info blahblahblah', 'module': 't', 'name': '__main__', 'process': (id=544, name='MainProcess'), 'thread': (
id=22864, name='MainThread'), 'time': datetime(2022, 5, 4, 19, 46, 30, 985198, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '中国标准时间'))}
Traceback (most recent call last):
  File "D:\miniconda3\envs\jxr151t\lib\site-packages\loguru\_handler.py", line 104, in emit
    if not self._filter(record):
  File "d:\WORK\JXR151T_VERIFY_BOARD\VerifyConsoleJXR151T_V020\t.py", line 15, in <lambda>
    li.append(logger.add("6.log", enqueue=True, filter=lambda record: record["extra"]["chip"] == 6))
KeyError: 'chip'
--- End of logging error ---
```

**Comment by Delgan** [comment]
Thanks. That's because not all loggers are bound with the `chip` parameter. Consequently, when you use `logger.info()` directly (without calling `bind()`) the `record["extra"]["chip"]` value does not exist. Try settings a default one globally at the beginning of your file:

```python
logger.configure(extra={"chip": None})
```

**Comment by KafCoppelia** [comment]
My hero! 🌹
Besides, if I wanna output log on my console and write into logs by `bind(...)` as above, there is no need to `logger.remove()` and then `logger.add(sys.stderr)` ath the beginning of my code?

**Comment by Delgan** [comment]
Indeed, this is not required because you are re-adding the `sys.stderr` without any modification to the others parameters. That means you are re-adding the default sink, while you don't need to if you don't call `logger.remove()` beforehand.

**Comment by KafCoppelia** [comment]
Thank you!
