### ISSUE TITLE
0.6.0: sphinx fails

### ISSUE THREAD

**Issue by kloczek** [Delgan/loguru#662]
Looks like it is some issue with generate documentation
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
  File "/home/tkloczko/rpmbuild/BUILD/loguru-0.6.0/docs/_extensions/autodoc_stub_file.py", line 37, in setup
    docstring = get_module_docstring(stub_path)
  File "/home/tkloczko/rpmbuild/BUILD/loguru-0.6.0/docs/_extensions/autodoc_stub_file.py", line 21, in get_module_docstring
    with open(filepath) as file:
FileNotFoundError: [Errno 2] No such file or directory: '../loguru/__init__.pyi'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/loguru-0.6.0/docs/_extensions/autodoc_stub_file.py", line 21, in get_module_docstring
    with open(filepath) as file:
FileNotFoundError: [Errno 2] No such file or directory: '../loguru/__init__.pyi'
The full traceback has been saved in /tmp/sphinx-err-261gg8q2.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@devel-g2v SPECS]$ cat /tmp/sphinx-err-261gg8q2.log
# Sphinx version: 4.5.0
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
  File "/home/tkloczko/rpmbuild/BUILD/loguru-0.6.0/docs/_extensions/autodoc_stub_file.py", line 37, in setup
    docstring = get_module_docstring(stub_path)
  File "/home/tkloczko/rpmbuild/BUILD/loguru-0.6.0/docs/_extensions/autodoc_stub_file.py", line 21, in get_module_docstring
    with open(filepath) as file:
FileNotFoundError: [Errno 2] No such file or directory: '../loguru/__init__.pyi'
```

**Comment by Delgan** [comment]
Hi @kloczek, thanks for the report!

This error happens because Loguru uses a relative path during docs generation: https://github.com/Delgan/loguru/blob/a3e15d27ca78c05bb7ebf6afc5bb83e4122980a9/docs/_extensions/autodoc_stub_file.py#L36

The path is relative to current working directory. Consequently, the docs must be generated from the `docs` directory to succeed.

I'll replace it with an absolute path based on `__file__` instead.

**Comment by Delgan** [comment]
Also here: https://github.com/Delgan/loguru/blob/a3e15d27ca78c05bb7ebf6afc5bb83e4122980a9/docs/conf.py#L18-L19

**Comment by kloczek** [comment]
> This error happens because Loguru uses a relative path during docs generation:

OK so .. sphiinx-build firs changes current directory to the location where is conf.py file.

**Comment by Delgan** [comment]
@kloczek It's not `sphinx-build` which changes the current directory, it just depends from where the command is executed.

You can get rid of the errors by calling `sphinx-build -n -T -b man . build/sphinx/man` (note the `docs` replaced with `.`) from within the `docs` folder.

**Comment by kloczek** [comment]
I'll give you some context. I'm building python modules as rpm packages and I'm using standard rpm macro to build module documentation using standardised procedure.
This is that macro
```spec
%sphinx_build   /usr/bin/sphinx-build
%sphinx_build_man() %{expand:\\\
        PBR_VERSION=%(v=%{version}; echo ${v%~*}) \\\
        PDM_PEP517_SCM_VERSION=%(v=%{version}; echo ${v%~*}) \\\
        SETUPTOOLS_SCM_PRETEND_VERSION=%(v=%{version}; echo ${v%~*}) \\\
        %sphinx_build -n -T -b man %["%{*}"?"%{*}":"docs"] build/sphinx/man}
```
That macro works on scale:
```console
[tkloczko@devel-g2v SPECS]$ grep ^%py3_build_sphinx_man python-* | wc -l; grep %%sphinx_build_man python-* | wc -l; ls -1 python-*| wc -l
112
438
958
```
I still have 112 packages to move from sphinx<>setuptools integration (`setup.py build_sphinx`). to new procedure which uses straight `sphinx-buid` command (setuptools `build_sphinx` is already marked as deprecated and many modules already are no longer using setuptools as pep517 backend).
I'm building modules documentation using both techniques +2 years.
I want only to say that it would be first ever my module which requires change directory to location where is conf.py file.

**Comment by Delgan** [comment]
Thanks for the additional information. I just wanted to give a short term workaround but it will be fixed so that it works in any case.

**Comment by kloczek** [comment]
Thank you 👍

**Comment by Delgan** [comment]
Fixed on `master` branch. ;)
