### ISSUE TITLE
Set extra record cause "KeyError" issue in FastAPI

### ISSUE THREAD

**Issue by GGGoingdown** [Delgan/loguru#676]
When i set some extra record in fastAPI startup event caused something error
### Versions:
- python 3.8.12
- loguru 0.6.0
- fastapi 0.75
--- 
### Code:
```
def logger_init():
    logger.remove()
    logger.add(
        sys.stdout,
        format="{extra[event]}",
    )
   context_logger = logger.bind(event="access")
   return context_logger

app = FastAPI()
@app.on_event("startup")
async def startup_event():
    logger = logger_init()
    logger.info("Start up")
       

```
---
### Error message : 
```
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(microseconds=270683), 'exception': None, 'extra': {}, 'file': (name='__init__.py', path='/app/./app/__init__.py'), 'function': 'startup_event', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 100, 'message': '--- Startup Event ---', 'module': '__init__', 'name': 'app', 'process': (id=229, name='SpawnProcess-102'), 'thread': (id=139944207652672, name='MainThread'), 'time': datetime(2022, 7, 6, 14, 51, 4, 487669, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/loguru/_handler.py", line 155, in emit
    formatted = precomputed_format.format_map(formatter_record)
KeyError: 'event'
--- End of logging error ---
```

**Comment by x931890193** [comment]
> When i set some extra record in fastAPI startup event caused something error
> 
> ### Versions:
> * python 3.8.12
> * loguru 0.6.0
> * fastapi 0.75
> 
> ### Code:
> ```
> def logger_init():
>     logger.remove()
>     logger.add(
>         sys.stdout,
>         format="{extra[event]}",
>     )
>    context_logger = logger.bind(event="access")
>    return context_logger
> 
> app = FastAPI()
> @app.on_event("startup")
> async def startup_event():
>     logger = logger_init()
>     logger.info("Start up")
>        
> ```
> 
> ### Error message :
> ```
> --- Logging error in Loguru Handler #1 ---
> Record was: {'elapsed': datetime.timedelta(microseconds=270683), 'exception': None, 'extra': {}, 'file': (name='__init__.py', path='/app/./app/__init__.py'), 'function': 'startup_event', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 100, 'message': '--- Startup Event ---', 'module': '__init__', 'name': 'app', 'process': (id=229, name='SpawnProcess-102'), 'thread': (id=139944207652672, name='MainThread'), 'time': datetime(2022, 7, 6, 14, 51, 4, 487669, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/loguru/_handler.py", line 155, in emit
>     formatted = precomputed_format.format_map(formatter_record)
> KeyError: 'event'
> --- End of logging error ---
> ```
### Yes it is a bug!!!
```python

from loguru import logger
logger.error("{qwer}", 'sss'). # when you log something with `{}` and add somthing string in it, it can make KeyError
# why?
# file   _logger.py

line 1952        elif args or kwargs:
line 1953             colored_message = None
line 1954             log_record["message"] = message.format(*args, **kwargs) # This is why there are bugs


```

**Comment by Delgan** [comment]
The issue is different from the one reported by @x931890193.

@GGGoingdown I'm unable to reproduce your error. The message is correctly printed on my terminal when I run `uvicorn main:app`. Please can you provide a fully reproducible example including all steps required to reproduce this issue?

**Comment by Delgan** [comment]
@GGGoingdown Thanks for the fully reproducible example.

The `provider` value is only present in the logger object returned by `.bind()`. The `extra` dict of default `logger` is empty, which causes a `KeyError` during formatting. You can set a default value with `logger.configure(extra={"provider": None})` for example.

**Comment by GGGoingdown** [comment]
@Delgan Thanks a lot. It works.
I have another question about formatting. If I  want to add additional metadata, **not in extra** records like ECS example
How can i do that ?
### ECS Example code
```
import logging
import ecs_logging

# Get the Logger
logger = logging.getLogger("app")
logger.setLevel(logging.DEBUG)

# Add an ECS formatter to the Handler
handler = logging.StreamHandler()
handler.setFormatter(ecs_logging.StdlibFormatter())
logger.addHandler(handler)

# Emit a log!
logger.debug("Example message!", extra={"http.request.method": "get"})
```
### ECS  Output
```
{
    "@timestamp": "2020-03-20T18:11:37.895Z",
    "log.level": "debug",
    "message": "Example message!",
    "ecs": {
        "version": "1.6.0"
    },
    "http": {
      "request": {
        "method": "get"
      }
    },
    "log": {
        "logger": "app",
        "origin": {
            "file": {
                "line": 14,
                "name": "test.py"
            },
            "function": "func"
        },
        "original": "Example message!"
    }
}
```

**Comment by Delgan** [comment]
@GGGoingdown Can you use the `bind()` method again? Like so:

```python
logger.bind(http_request_method="get").debug("Example message!")
```

**Comment by Delgan** [comment]
Alternatively, you can take a look at the [`patch()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.patch) method which give more control (as you can access the entire `record`).

**Comment by GGGoingdown** [comment]
@Delgan  Yap! It can add in extra key record. But I want to add **outside** the extra key.
### For example:
```
logger.add(sys.stderr, format="{event[dataset]} {extra[provider]}")
logger.bind(event="login", provider="api")
```
### Expected output:
```
{
 "event": "login",
 "extra": {
     "provider": "api"
  }
}
```
