### ISSUE TITLE
"ValueError: call stack is not deep enough" while using "atexit.register"

### ISSUE THREAD

**Issue by Delgan** [Delgan/loguru#680]
> This one caught me with the following pattern:
> ```python
> import atexit
> from loguru import logger
> 
> 
> logger.info('Hi!')
> atexit.register(logger.info, 'Bye!')
> 
> logger.info('Doing stuff...')
> ```
> ```shell
> 2022-07-06 11:50:55.989 | INFO     | __main__:<module>:6 - Hi!
> 2022-07-06 11:50:55.989 | INFO     | __main__:<module>:8 - Doing stuff...
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/hannes/work/repos/loguru/loguru/_logger.py", line 1974, in info
>     __self._log("INFO", None, False, __self._options, __message, args, kwargs)
>   File "/home/hannes/work/repos/loguru/loguru/_logger.py", line 1852, in _log
>     frame = get_frame(depth + 2)
> ValueError: call stack is not deep enough
> 
> ```

 _Originally posted by @astromancer in https://github.com/Delgan/loguru/issues/88#issuecomment-1176028447_

**Comment by Delgan** [comment]
@xzmeng Yes, that's exactly this.

It's fixed in #1240. The shared snippet will now produce the following output without error:

```
2024-11-26 17:36:21.883 | INFO     | __main__:<module>:5 - Hi!
2024-11-26 17:36:21.883 | INFO     | __main__:<module>:8 - Doing stuff...
2024-11-26 17:36:21.883 | INFO     | None:<unknown>:0 - Bye!
```

The context information is missing because there it's not available (sine there is no frame).

As a workaround, I recommend to create a dedicated function:

```python
import atexit
from loguru import logger


def on_exit():
    logger.info("Bye!")


logger.info("Hi!")
atexit.register(on_exit)

logger.info("Doing stuff...")
```
