### ISSUE TITLE
Set limit to output traceback

### ISSUE THREAD

**Issue by moonvent** [Delgan/loguru#730]
Hi! I need to set limit on traceback, I search internet about that, but I didn't found solution about that. I try to override traceback object, but I cannot do that, I want that traceback printed by `logger.exception` was string from my code, exception, and a **one** string from library with call this exception, example I attach below:

What I have: 
```

2022-10-21 16:38:23.341 | ERROR    | __main__:test:61 - Oops
Traceback (most recent call last):

  File "/Users/lol/PycharmProjects/test310/test_logs.py", line 89, in <module>
    test()
    └ <function test at 0x1025f3eb0>

> File "/Users/lol/PycharmProjects/test310/test_logs.py", line 57, in test
    requests.get('hstps://google.com')
    │        └ <function get at 0x10e695510>
    └ <module 'requests' from '/Users/lol/PycharmProjects/test310/venv/lib/python3.10/site-packages/requests/__init__.py'>

  File "/Users/lol/PycharmProjects/test310/venv/lib/python3.10/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {}
           │              │           └ None
           │              └ 'hstps://google.com'
           └ <function request at 0x10e661a20>
  File "/Users/lol/PycharmProjects/test310/venv/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None}
           │       │              │           └ 'hstps://google.com'
           │       │              └ 'get'
           │       └ <function Session.request at 0x10e694ca0>
           └ <requests.sessions.Session object at 0x104d0d480>
  File "/Users/lol/PycharmProjects/test310/venv/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x10e695120>
           └ <requests.sessions.Session object at 0x104d0d480>
  File "/Users/lol/PycharmProjects/test310/venv/lib/python3.10/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
              │    │               │       └ 'hstps://google.com'
              │    │               └ <PreparedRequest [GET]>
              │    └ <function Session.get_adapter at 0x10e695240>
              └ <requests.sessions.Session object at 0x104d0d480>
  File "/Users/lol/PycharmProjects/test310/venv/lib/python3.10/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
          │                                                                 └ 'hstps://google.com'
          └ <class 'requests.exceptions.InvalidSchema'>

requests.exceptions.InvalidSchema: No connection adapters were found for 'hstps://google.com'
```

What I need:

```
2022-10-21 16:38:23.341 | ERROR    | __main__:test:61 - Oops
Traceback (most recent call last):

  File "/Users/lol/PycharmProjects/test310/test_logs.py", line 89, in <module>
    test()
    └ <function test at 0x1025f3eb0>

> File "/Users/lol/PycharmProjects/test310/test_logs.py", line 57, in test
    requests.get('hstps://google.com')
    │        └ <function get at 0x10e695510>
    └ <module 'requests' from '/Users/lol/PycharmProjects/test310/venv/lib/python3.10/site-packages/requests/__init__.py'>

  File "/Users/lol/PycharmProjects/test310/venv/lib/python3.10/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
          │                                                                 └ 'hstps://google.com'
          └ <class 'requests.exceptions.InvalidSchema'>

requests.exceptions.InvalidSchema: No connection adapters were found for 'hstps://google.com'
```

Thanks for attention!

**Comment by Delgan** [comment]
Hi.

You can configure your handler with `backtrace=False`.

**Comment by Delgan** [comment]
My bad, I think I read too fast.

It's probably not possible, because this is how Python traceback work: it displays the source of the `Exception` up to the `try / catch` block.

You'll need to write a custom exception formatter or use an existing one which provide the feature you're looking for.

**Comment by moonvent** [comment]
> My bad, I think I read too fast.
> 
> It's probably not possible, because this is how Python traceback work: it displays the source of the `Exception` up to the `try / catch` block.
> 
> You'll need to write a custom exception formatter or use an existing one which provide the feature you're looking for.

But I try `traceback.print_exc(limit=1)` and it's fine for me, can I override loguru traceback object for this result? Below result of this code:

```
Traceback (most recent call last):
  File "/Users/lol/PycharmProjects/test310/test_logs.py", line 59, in test
    requests.get('hstps://google.com')
requests.exceptions.InvalidSchema: No connection adapters were found for 'hstps://google.com'
```

**Comment by Delgan** [comment]
Thanks for the example @moonvent, I didn't know about the `limit` argument.

For the moment I don't have an ideal solution for you, the best is to implement your own formatter as suggested in the documentation: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).

**Comment by moonvent** [comment]
> Thanks for the example @moonvent, I didn't know about the `limit` argument.
> 
> For the moment I don't have an ideal solution for you, the best is to implement your own formatter as suggested in the documentation: [Customizing the formatting of exceptions](https://loguru.readthedocs.io/en/stable/resources/recipes.html#customizing-the-formatting-of-exceptions).
> 
> You'll be able to use `limit=1` but you'll lose the variable values displayed. You may need to use another exception formatter, then.

Ohoho( Solution for me it's

```
def test():
    try:
        requests.get('hstps://google.com')
    except Exception as e:
        create_exception_log()


def create_exception_log():
    logger.error(traceback.format_exc(limit=1))


test()
```

A chapter of docs which you give me don't answer on my question, and on the countrary give me not what I need, thaks for your helping and maybe you think about this proposition on next version of updates!) Thanks!
