### ISSUE TITLE
KeyError when using character "{" in string message and using extra

### ISSUE THREAD

**Issue by alexsanderp** [Delgan/loguru#762]
When using dictionary inside the string set as message in the logger and using extra at the same time we have a KeyError problem.

Version: 0.6.0

Code to reproduce:

```
from loguru import logger

logger.info("testing alex with {'alex': 'alex'}", extra={"test": "test"})
```

Output:
```
Traceback (most recent call last):
  File "/home/alex/code/dadosfera/logs-python-lib/examples/test.py", line 3, in <module>
    logger.info("testing alex with {'alex': 'alex'}", extra={"test": "test"})
  File "/home/alex/.cache/pypoetry/virtualenvs/dadosfera-logs-F6RWpcEw-py3.10/lib/python3.10/site-packages/loguru/_logger.py", line 1977, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File "/home/alex/.cache/pypoetry/virtualenvs/dadosfera-logs-F6RWpcEw-py3.10/lib/python3.10/site-packages/loguru/_logger.py", line 1954, in _log
    log_record["message"] = message.format(*args, **kwargs)
KeyError: "'alex'"
```

**Comment by alexsanderp** [comment]
I found other errors using {

```
from loguru import logger

logger.info("testing alex with {", extra={"test": "test"})
```

Output:
```
Traceback (most recent call last):
  File "/home/alex/code/dadosfera/logs-python-lib/examples/test.py", line 3, in <module>
    logger.info("testing alex with {", extra={"test": "test"})
  File "/home/alex/.cache/pypoetry/virtualenvs/dadosfera-logs-F6RWpcEw-py3.10/lib/python3.10/site-packages/loguru/_logger.py", line 1977, in info
    __self._log("INFO", None, False, __self._options, __message, args, kwargs)
  File "/home/alex/.cache/pypoetry/virtualenvs/dadosfera-logs-F6RWpcEw-py3.10/lib/python3.10/site-packages/loguru/_logger.py", line 1954, in _log
    log_record["message"] = message.format(*args, **kwargs)
ValueError: Single '{' encountered in format string
```

**Comment by Delgan** [comment]
Loguru will call `message.format(*args, **kwargs)` when it detects arguments:

```python
logger.info("Value is: {value}", value=123)  # => "Value is: 123"
```
If your message contains braces which are not intended for formatting, then the error you're facing will happen.

A possible workaround is to escape formatting by using double-braces:

```python
logger.info("testing alex with {{'alex': 'alex'}}", extra={"test": "test"})
```

Another possibility is to use `.bind()` instead of keyword arguments:

```python
logger.bind(extra={"test": "test"}).info("testing  alex with {'alex': 'alex'}")
```

**Comment by alexsanderp** [comment]
The problem comes from intercepting the logs coming from Python's logging.

**But the bind solves my problem.** :)

Before:
```
class DadosferaLoggingInterceptHandler(logging.Handler):
    def emit(self, record):
        ...
        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage(), **extras)
```

After:

```
class DadosferaLoggingInterceptHandler(logging.Handler):
    def emit(self, record):
        ...
        logger.bind(extras=extras, depth=depth, exception=record.exc_info).log(level, record.getMessage())
```

**Comment by alexsanderp** [comment]
I will mark an issue as done!
