### ISSUE TITLE
logger occurred KeyError if dict in message and kwargs exists

### ISSUE THREAD

**Issue by wildwolfeng** [Delgan/loguru#781]
## Description

```py
from loguru import logger

msg = "this is a dict: {'a': 1, 'b': 2}"

logger.debug(msg, kw='extra_args')

```

Above code will failed with output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fyu/.local/lib/python3.10/site-packages/loguru/_logger.py", line 1973, in debug
    __self._log("DEBUG", None, False, __self._options, __message, args, kwargs)
  File "/home/fyu/.local/lib/python3.10/site-packages/loguru/_logger.py", line 1954, in _log
    log_record["message"] = message.format(*args, **kwargs)
KeyError: "'a'"
```

**Comment by Delgan** [comment]
Loguru will call `message.format(*args, **kwargs)` when it detects arguments:

```python
logger.info("Value is: {value}", value=123)  # => "Value is: 123"
```
If your message contains braces which are not intended for formatting, then a `KeyError` will happen.

A possible workaround is to escape formatting by using double-braces:

```python
logger.info("this is a dict: {{'a': 1, 'b': 2}}", kw='extra_args')
```

Another possibility is to use `.bind()` instead of keyword arguments:

```python
logger.bind(kw='extra_args').info("this is a dict: {{'a': 1, 'b': 2}}")
```

**Comment by wildwolfeng** [comment]
@Delgan Thanks for your reply, it is useful to me.
