### ISSUE TITLE
ExceptionGroup support

### ISSUE THREAD

**Issue by nanouasyn** [Delgan/loguru#805]
In python 3.11, an `ExceptionGroup` exception has been added, which represents several exceptions raised independently at the same time.

Here is an example. Two tasks are performed in parallel. Both raise different unrelated exceptions. Exceptions are wrapped in an ExceptionGroup and raised:

```python
import asyncio

async def f1():
    2 / 0

async def f2():
    max()

async def main():
    async with asyncio.TaskGroup() as tg:
        tg.create_task(f1())
        tg.create_task(f2())

asyncio.run(main())
```

Let's look at the behavior of the default traceback printer:

```
  + Exception Group Traceback (most recent call last):
  |   File "/home/nanousyn/a.py", line 14, in <module>
  |     asyncio.run(main())
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/home/nanousyn/a.py", line 10, in main
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 133, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/nanousyn/a.py", line 4, in f1
    |     2 / 0
    |     ~~^~~
    | ZeroDivisionError: division by zero
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/nanousyn/a.py", line 7, in f2
    |     max()
    | TypeError: max expected at least 1 argument, got 0
    +------------------------------------
```

We see both exceptions along with their tracebacks. But what about loguru?

```python
import asyncio
from loguru import logger

async def f1():
    2 / 0

async def f2():
    max()

@logger.catch
async def main():
    async with asyncio.TaskGroup() as tg:
        tg.create_task(f1())
        tg.create_task(f2())

asyncio.run(main())
```

```
2023-02-25 05:31:31.292 | ERROR    | asyncio.events:_run:80 - An error has been caught in function '_run', process 'MainProcess' (4626), thread 'MainThread' (140663743039296):
Traceback (most recent call last):

  File "/home/nanousyn/a.py", line 16, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7feed19ff4c0>
    │       └ <function run at 0x7feed225a660>
    └ <module 'asyncio' from '/usr/lib/python3.11/asyncio/__init__.py'>

  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x7feed1985540>
           │      └ <function Runner.run at 0x7feed225e840>
           └ <asyncio.runners.Runner object at 0x7feed226fd50>
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task cancelling name='Task-1' coro=<main() running at /home/nanousyn/python3.11-env/lib/python3.11/site-packages/loguru/_log...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x7feed225c4a0>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7feed226fd50>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7feed225c400>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7feed225e200>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7feed21bc860>
    └ <Handle Task.task_wakeup(<Future cancelled>)>
> File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future cancelled>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future cancelled>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future cancelled>)>

  File "/home/nanousyn/a.py", line 12, in main
    async with asyncio.TaskGroup() as tg:
               │       │              └ <TaskGroup cancelling>
               │       └ <class 'asyncio.taskgroups.TaskGroup'>
               └ <module 'asyncio' from '/usr/lib/python3.11/asyncio/__init__.py'>

  File "/usr/lib/python3.11/asyncio/taskgroups.py", line 133, in __aexit__
    raise me from None
          └ ExceptionGroup('unhandled errors in a TaskGroup', [ZeroDivisionError('division by zero'), TypeError('max expected at least 1 ...

ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
```

We don't see all the exceptions contained in `ExceptionGroup`. And the exception that we still see does not have a traceback.

**Comment by Delgan** [comment]
Thanks for the report. It's definitely something I'll be looking at.
