### ISSUE TITLE
NotificationHandler broken when logging exception

### ISSUE THREAD

**Issue by 00sapo** [Delgan/loguru#821]
Not sure this is a bug:

```python
import json
from loguru import logger
from notifiers.logging import NotificationHandler

auth = json.load(open("./telegram.json"))
telegram_handler = NotificationHandler("telegram", defaults=auth)
logger.add(telegram_handler, level="ERROR")

logger.error("Error!") # works
try:
  a = 1/0
except:
  logger.exception("exception") # fails during handling by NotificationHandler
```

This simple example works, but when the log message is longer, I get the following:
```
Traceback (most recent call last):
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/notifiers/logging.py", line 50, in emit
    self.provider.notify(raise_on_errors=True, **data)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/notifiers/core.py", line 303, in notify
    data = self._process_data(**kwargs)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/notifiers/core.py", line 235, in _process_data
    self._validate_data(data)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/notifiers/core.py", line 208, in _validate_data
    raise BadArguments(validation_error=msg, provider=self.name, data=data)
notifiers.exceptions.BadArguments: Error with sent data: '2023-03-14 15:45:03.600 [...]' is too long
Call stack:
  File "/home/federico/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/federico/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/federico/symbolic_features/symbolic_features/effectiveness.py", line 126, in <module>
    fire.Fire(Main)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/federico/symbolic_features/symbolic_features/effectiveness.py", line 99, in classification
    logger.exception("An exception occured!")
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/loguru/_logger.py", line 1998, in exception
    __self._log("ERROR", None, False, options, __message, args, kwargs)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/loguru/_logger.py", line 1965, in _log
    handler.emit(log_record, level_id, from_decorator, raw, colored_message)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/loguru/_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/loguru/_simple_sinks.py", line 50, in write
    self._handler.handle(record)
  File "/home/federico/.pyenv/versions/3.10.9/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/home/federico/symbolic_features/.venv/lib/python3.10/site-packages/notifiers/logging.py", line 52, in emit
    self.handleError(record)
Message: '2023-03-14 15:45:03.600 [...]'
Arguments: ()
```

notifiers version: 1.3.0
loguru version: 0.6.0
python version: 3.10.9

**Comment by 00sapo** [comment]
The problem seems to be connected with the length of the message, see this line in the stack trace:

`notifiers.exceptions.BadArguments: Error with sent data: '2023-03-14 15:45:03.600 [...]' is too long`

**Comment by 00sapo** [comment]
See https://github.com/liiight/notifiers/issues/398

**Comment by Delgan** [comment]
Hey @00sapo.

I suppose it doesn't qualify as a bug from Loguru side, as it's a limitation from `notifiers` and the Telegram API.

A possible workaround would be to use a custom sink to truncate the message if it's too long:

```python
with open("./telegram.json") as file:
    auth = json.load(file)

def telegram_sink(message):
    notifier = notifiers.get_notifier("telegram")
    notifier.notify(message=message[:4096], **auth)

logger.add(telegram_sink, level="ERROR")
```
