### ISSUE TITLE
cannot pickle '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by weidongzhou1994** [Delgan/loguru#831]
When I use the loguru in  multiprocessing on mac, it suddenly raise this error: cannot pickle '_io.TextIOWrapper' object.
This is my code:
```python
with Pool(len(all_strategy), initializer=set_global_logger, initargs=(logger, )) as inner_pool:
    all_res = inner_pool.starmap(run_heuristic, [(data, trans_data, trans_date, strategy, slaughter, cust_area, order_date, is_heru) for strategy in all_strategy])
```

**Comment by Delgan** [comment]
Which handlers are configured to be used by your `logger`? Are you using `enqueue=True`?

**Comment by weidongzhou1994** [comment]
```python
def update_formatter(record):
    from config import TASKID
    record["extra"]["stack"] = TASKID
    return "任务ID: {extra[stack]} | {time:YYYY-MM-DD HH:mm:ss} {level} {message}\n"

def save_log(logger, save_type="sys", file_path=None):
    """保存日志：定义日志格式和输出方式"""
    logger.remove()
    # logger.add(sys.stderr, format="{time:YYYY-MM-DD HH:mm:ss} {level} {message}", level="DEBUG", enqueue=True)
    if save_type == "local" and file_path:
        logger = logger.add(sink=file_path, format=update_formatter, enqueue=True)
    elif save_type == "sys":
        logger = logger.add(sink=sys.stdout, format=update_formatter, enqueue=True)
    elif save_type == "online":
        handler = CMRESHandler(hosts=[{'host': '127.0.0.1', 'port': 9200}],
                           auth_type=CMRESHandler.AuthType.NO_AUTH,
                           es_index_name="my_python_index")
        logger = logger.add(sink=handler, format=update_formatter, enqueue=True)

```

**Comment by Delgan** [comment]
When passing the `logger` to a child process, the `logger` itself must be pickable.
Also, when `enqueue=True`, the logged messages must be picklable.

It seems one of these two conditions is not met.
It is difficult for me to help you further without a fully reproducible example. The thrown exception should contain a stack trace indicating the location in your code where the error originated.

**Comment by weidongzhou1994** [comment]
When I put the logger to multiprocessing, it raise this exception, so the first conditions were not met.

**Comment by Delgan** [comment]
Although any handler is pickable as long as it's added with `enqueue=True`.

Any chance you can share an example reproducing the exception?

**Comment by weidongzhou1994** [comment]
Maybe the logger info can't be pickled when the info is too long?

**Comment by weidongzhou1994** [comment]
This is the run code:
```python
from loguru import logger
from demo import test, set_global_logger
from multiprocessing import Pool


def run():
    with Pool(3, initializer=set_global_logger, initargs=(logger, )) as inner_pool:
        inner_pool(test, [(i,) for i in range(3)])
    


if __name__ == "__main__":
    run()
```

This is the logger code:
```python
def set_global_logger(logger_):
    global logger
    logger = logger_


def test(i):
    logger.info("This is a test message!")
```

**Comment by weidongzhou1994** [comment]
Maybe the logger message can't pickle? The code has changed, and the way of building the logger has changed from put to inner build.

**Comment by Delgan** [comment]
Maybe. I can't say more unfortunately.

**Comment by weidongzhou1994** [comment]
Thanks for your reply. If I encounter the same problem next time, I would put the code.

**Comment by Delgan** [comment]
Yes, code and traceback of the excpetion would be great. :+1:

**Comment by Tayamarn** [comment]
Hello!

I just happened to stumble upon this on mac as well.

Code to reproduce:
```
from loguru import logger
import multiprocessing as mp


def check_mp(num, _logger):
    _logger.info(f"test {num}")

def check_mp2(num):
    logger.info(f"test {num}")

def main():
    logger.add(
        "test_log.txt",
        level="INFO",
        format="{time:YYYY-MM-DD HH:mm:ss.SSS zz} {level} | Line {line: >4} ({file}): {message}",
        colorize=False,
        backtrace=True,
        diagnose=True,
        enqueue=True,
    )
    proc = mp.Process(
        target=check_mp,
        args=(123, logger, )
    )
    proc.start()
    proc2 = mp.Process(
        target=check_mp2,
        args=(123, )
    )
    proc2.start()
    logger.info("in __main__")
    proc.join()
    proc2.join()

if __name__ == '__main__':
    main()

```

If I comment out all the lines with proc, everythong works well:
```
(.venv) tayamarn@Maksims-Laptop gigadoc_backend % python test_mp.py
2025-10-29 15:52:17.945 | INFO     | __main__:main:31 - in __main__
2025-10-29 15:52:17.983 | INFO     | __mp_main__:check_mp2:9 - test 123
```

With all the lines the code fails like this:
```
(.venv) tayamarn@Maksims-Laptop gigadoc_backend % python test_mp.py
Traceback (most recent call last):
  File "/Users/tayamarn/projects/gigadoc_backend/test_mp.py", line 36, in <module>
    main()
  File "/Users/tayamarn/projects/gigadoc_backend/test_mp.py", line 25, in main
    proc.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object
```


My versions:
```
(.venv) tayamarn@Maksims-Laptop gigadoc_backend % python --version
Python 3.11.9
(.venv) tayamarn@Maksims-Laptop gigadoc_backend % pip freeze | grep loguru
loguru==0.7.3
(.venv) tayamarn@Maksims-Laptop gigadoc_backend % system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 14.3 (23D2057)
      Kernel Version: Darwin 23.3.0
```

Hope it helps!

**Comment by Delgan** [comment]
Hi @Tayamarn.

This error occurs because of the default handler, namely `sys.stderr`, which unfortunately cannot be pickled.

Make sure to `remove()` it first, then re-`add()` with the `enqueue=True` option:

```python
from loguru import logger
import multiprocessing as mp
import sys

def check_mp(num, _logger):
    _logger.info(f"test {num}")


def check_mp2(num):
    logger.info(f"test {num}")


def main():
    logger.remove()   # Remove the default handler.
    logger.add(sys.stderr, enqueue=True)
    logger.add(
        "test_log.txt",
        level="INFO",
        format="{time:YYYY-MM-DD HH:mm:ss.SSS zz} {level} | Line {line: >4} ({file}): {message}",
        colorize=False,
        backtrace=True,
        diagnose=True,
        enqueue=True,
    )
    proc = mp.Process(
        target=check_mp,
        args=(
            123,
            logger,
        ),
    )
    proc.start()
    proc2 = mp.Process(target=check_mp2, args=(123,))
    proc2.start()
    logger.info("in __main__")
    proc.join()
    proc2.join()


if __name__ == "__main__":
    main()
```

That should work fine.

I could add this information to the "Troubleshooting" page of the docs, though.
