### ISSUE TITLE
ValueError: Max string recursion exceeded

### ISSUE THREAD

**Issue by ch1762** [Delgan/loguru#841]
```
Traceback (most recent call last):
  File "/Users/ch/miniconda3/lib/python3.8/site-packages/loguru/_logger.py", line 911, in add
    formatter = Colorizer.prepare_format(format + terminator + "{exception}")
  File "/Users/ch/miniconda3/lib/python3.8/site-packages/loguru/_colorizer.py", line 358, in prepare_format
    tokens, messages_color_tokens = Colorizer._parse_without_formatting(string)
  File "/Users/ch/miniconda3/lib/python3.8/site-packages/loguru/_colorizer.py", line 467, in _parse_without_formatting
    _, color_tokens = Colorizer._parse_without_formatting(
  File "/Users/ch/miniconda3/lib/python3.8/site-packages/loguru/_colorizer.py", line 467, in _parse_without_formatting
    _, color_tokens = Colorizer._parse_without_formatting(
  File "/Users/ch/miniconda3/lib/python3.8/site-packages/loguru/_colorizer.py", line 467, in _parse_without_formatting
    _, color_tokens = Colorizer._parse_without_formatting(
  File "/Users/ch/miniconda3/lib/python3.8/site-packages/loguru/_colorizer.py", line 439, in _parse_without_formatting
    raise ValueError("Max string recursion exceeded")
ValueError: Max string recursion exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ch/work/woody-manager/controller/record_log.py", line 35, in wrapper
    LOGGER().info(dlag="_com_request_out", uri=str(request.path), proc_time=proc_time, trace_id=trace_id,
  File "/Users/ch/work/woody-manager/utils/LOGGER.py", line 63, in info
    logger.add(self.info_filename, format=log_format, rotation="00:00", retention='30 days',
  File "/Users/ch/miniconda3/lib/python3.8/site-packages/loguru/_logger.py", line 913, in add
    raise ValueError(
ValueError: Invalid format, color markups could not be parsed correctly
```

Hello, I encountered the above problems when I used Loguru. Due to the printed parameters, the parameters were too long, which caused ERROR. How do I need to solve this problem?

**Comment by Delgan** [comment]
Hi.

Could you please share the implementation of your `LOGGER()` function?
Also, do you know the value of `log_format` variable at the time of the exception?

Without more information, it is unfortunately difficult for me to understand where the problem comes from.
