### ISSUE TITLE
Async DataBaseHandler (Sink?) Django

### ISSUE THREAD

**Issue by zN3utr4l** [Delgan/loguru#879]
I wrote this **db logger for version 0.6.0**, I'm still in this one, I'll update soon.
I have a **celery** service which runs tasks with **gevent**.
Task where I parallelize a function. 
Example:
```
from multiprocessing.pool import ThreadPool
from loguru import logger

def my_func(msg):
    logger_mp = logger.bind(enqueue=True)
    logger_mp.info(msg)
    logger_mp.complete()
    
ThreadPool(2).map(my_func, [msg, msg, msg])
```

**Logger Handler:**
```
import logging
from ..models import Log
from loguru import logger
from logger.service.unitofwork import log_repository
import asyncio
from asgiref.sync import sync_to_async
import nest_asyncio


class DatabaseLogHandler(logging.Handler):
    def emit(self, record):
        try:
            level = logger.level(record.levelname).name

        except ValueError:
            level = logging._levelToName[record.levelno]

        if level is None:
            level = logging._levelToName[logging.NOTSET]

        entity = Log(caller=record.filename, level=level, message=record.msg, logger=record.name, thread_id=record.thread, process_id=record.process, process_name=record.processName)

        if record.extra.get('enqueue', False):
            future = sync_to_async(log_repository.insert)(entity)

            self.log_db(future)

        else:
            log_repository.insert(entity)

    def log_db(self, future):
        try:
            loop = asyncio.get_event_loop()

            nest_asyncio.apply(loop)

            return asyncio.run(loop.create_task(future))

        except RuntimeError:  # no event loop running:
            loop = asyncio.new_event_loop()

            return loop.run_until_complete(loop.create_task(future))
            
            
            
            
            
logger.configure(**{'handlers': [
        {
            'sink': DatabaseLogHandler(),
            'catch': True,
            'backtrace': True,
            'diagnose': True,
            'format': '{message}',
            'level': 'INFO',
            # 'enqueue':True
        }
    ]}

```

**ERROR:**
```
Error in Loguru Handler #3 ---

2023-05-23T05:05:03.141819426Z [2023-05-23 05:05:03,141: INFO/MainProcess] Record was: {'elapsed': datetime.timedelta(seconds=55338, microseconds=885634), 'exception': None, 'extra': {'enqueue': True}, 'file': (name='test.py', path='/code/test.py'), 'function': 'my_func', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 114, 'message': 'test', 'module': 'service', 'name': 'code', 'process': (id=57, name='MainProcess'), 'thread': (id=140529039648384, name='Thread-3598'), 'time': datetime(2023, 5, 23, 5, 5, 3, 24465, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}

2023-05-23T05:05:03.142005366Z [2023-05-23 05:05:03,141: INFO/MainProcess] Traceback (most recent call last):

2023-05-23T05:05:03.142059909Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/asgiref/sync.py", line 486, in thread_handler

2023-05-23T05:05:03.142061992Z     raise exc_info[1]

2023-05-23T05:05:03.142095679Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/logger/service/database_log_handler.py", line 33, in log_db

2023-05-23T05:05:03.142103120Z     loop = asyncio.get_event_loop()

2023-05-23T05:05:03.142117095Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/asyncio/events.py", line 642, in get_event_loop

2023-05-23T05:05:03.142125134Z     raise RuntimeError('There is no current event loop in thread %r.'

2023-05-23T05:05:03.142148928Z [2023-05-23 05:05:03,142: INFO/MainProcess] RuntimeError: There is no current event loop in thread 'Thread-3598'.

2023-05-23T05:05:03.142177097Z [2023-05-23 05:05:03,142: INFO/MainProcess] 

2023-05-23T05:05:03.142179493Z During handling of the above exception, another exception occurred:

2023-05-23T05:05:03.142256815Z [2023-05-23 05:05:03,142: INFO/MainProcess] Traceback (most recent call last):

2023-05-23T05:05:03.142264155Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/loguru/_handler.py", line 177, in emit

2023-05-23T05:05:03.142266193Z     self._sink.write(str_record)

2023-05-23T05:05:03.142281897Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/loguru/_simple_sinks.py", line 50, in write

2023-05-23T05:05:03.142283640Z     self._handler.handle(record)

2023-05-23T05:05:03.142306679Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/logging/__init__.py", line 952, in handle

2023-05-23T05:05:03.142308337Z     self.emit(record)

2023-05-23T05:05:03.142336364Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/logger/service/database_log_handler.py", line 26, in emit

2023-05-23T05:05:03.142338448Z     self.log_db(future)

2023-05-23T05:05:03.142360277Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/logger/service/database_log_handler.py", line 42, in log_db

2023-05-23T05:05:03.142362880Z     return loop.run_until_complete(loop.create_task(future))

2023-05-23T05:05:03.142385223Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete

2023-05-23T05:05:03.142387550Z     return future.result()

2023-05-23T05:05:03.142413032Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/asgiref/sync.py", line 448, in __call__

2023-05-23T05:05:03.142415423Z     ret = await asyncio.wait_for(future, timeout=None)

2023-05-23T05:05:03.142434963Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/asyncio/tasks.py", line 442, in wait_for

2023-05-23T05:05:03.142437161Z     return await fut

2023-05-23T05:05:03.142460018Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run

2023-05-23T05:05:03.142462321Z     result = self.fn(*self.args, **self.kwargs)

2023-05-23T05:05:03.142484978Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/asgiref/sync.py", line 488, in thread_handler

2023-05-23T05:05:03.142488112Z     return func(*args, **kwargs)

2023-05-23T05:05:03.142508925Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/logger/service/generic_repository.py", line 53, in insert

2023-05-23T05:05:03.142513564Z     entity.save()

2023-05-23T05:05:03.142534408Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/logger/models.py", line 28, in save

2023-05-23T05:05:03.142536828Z     return super().save(force_insert, force_update, using, update_fields)

2023-05-23T05:05:03.142561943Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save

2023-05-23T05:05:03.142564427Z     self.save_base(using=using, force_insert=force_insert,

2023-05-23T05:05:03.142583232Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base

2023-05-23T05:05:03.142585459Z     updated = self._save_table(

2023-05-23T05:05:03.142607688Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/django/db/models/base.py", line 881, in _save_table

2023-05-23T05:05:03.142609916Z     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)

2023-05-23T05:05:03.142632176Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/django/db/models/base.py", line 919, in _do_insert

2023-05-23T05:05:03.142635559Z     return manager._insert(

2023-05-23T05:05:03.142656396Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

2023-05-23T05:05:03.142658705Z     return getattr(self.get_queryset(), name)(*args, **kwargs)

2023-05-23T05:05:03.142682206Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert

2023-05-23T05:05:03.142684522Z     return query.get_compiler(using=using).execute_sql(returning_fields)

2023-05-23T05:05:03.142706009Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1414, in execute_sql

2023-05-23T05:05:03.142708367Z     with self.connection.cursor() as cursor:

2023-05-23T05:05:03.142730347Z [2023-05-23 05:05:03,142: INFO/MainProcess]   File "/opt/conda/lib/python3.9/site-packages/django/utils/asyncio.py", line 31, in inner

2023-05-23T05:05:03.142732550Z     raise SynchronousOnlyOperation(message)

2023-05-23T05:05:03.142759778Z [2023-05-23 05:05:03,142: INFO/MainProcess] django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
```

**I think the error is the implementation of the Handler, should I have it inherit from loguru._handler.Handler or loguru._simple_sinks.AsyncSync?**

This can be a solution?
https://github.com/anfema/python-dblogger/blob/master/dblogger/async_handler.py

Thanks.

**Comment by zN3utr4l** [comment]
I found this question, it's exactly what happens to me.
https://stackoverflow.com/questions/65326908/synchronousonlyoperation-from-celery-task-using-gevent-execution-pool

**Comment by Delgan** [comment]
Hi, any chance you could share a minimal reproducible example?

You should not need to inherit from `loguru._handler.Handler` nor `loguru._simple_sinks.AsyncSync` (those are private classes).

I don't know how the `async` Django mechanism is expected to be used. Regarding Python, you can use basic synchronous sink or an asynchronous one. The sink will be called every time the logger is used, so it's up to you to adapt it to your framework.

For testing purpose, I suggest you to use a function to implement your custom database handler:

```python
def db_sync(record):
    log_repository.insert(record["message"])

async def db_async(record):
    await log_repository.insert(record["message"])

# Use one or the other
logger.add(db_sync)
logger.add(db_async)
```

**Comment by zN3utr4l** [comment]
minimum reproducible example I don't think, however the error occurs when starting a task celery, with rabbitmq and database (on docker), I'll try to give you an example.

```
celery==5.2.7
django==3.2.19
```

**celeryconfig.py**
```
from kombu import serialization
from datetime import timedelta
from django.conf import settings
import ssl

broker_url = settings.CELERY_RABBIT_MQ_HOST
cache_backend = 'django-db'
result_backend = 'django-db'
result_persistent = True
beat_scheduler = 'django_celery_beat.schedulers:DatabaseScheduler'
task_compression = 'gzip'
result_compression = 'gzip'
result_extended = True
result_expires = timedelta(weeks=2)
# if this is set to 0 or None, we’ll retry forever.
broker_connection_max_retries = None
broker_pool_limit = None
broker_transport_options = {'confirm_publish': True}
# json serializer is more secure than the default pickle
accept_content = ['json', 'pickle', 'application/x-python-serialize']
task_serializer = 'pickle'  # For pass argument to task
result_serializer = 'json'
serialization.register_pickle()
serialization.enable_insecure_serializers()
task_track_started = True
# Use UTC instead of localtime
timezone = 'UTC'
enable_utc = True
task_publish_retry = True
task_publish_retry_policy = {
    'interval_step': 0.2, 'max_retries': 3, 'interval_start': 0, 'interval_max': 1}
database_table_names = {
    'task': 'celery_task_result',
    'group': 'celery_group_result',
}
#task_time_limit = 3600
task_send_sent_event = True
worker_cancel_long_running_tasks_on_connection_loss = True
worker_send_task_events = True
worker_log_color = True
# Default:
#     '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
worker_log_format = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
# The format to use for log messages logged in tasks.
# Default:
#     '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'
worker_task_log_format = '[%(asctime)s: %(levelname)s/%(processName)s] %(task_name)s[%(task_id)s]: %(message)s'
worker_redirect_stdouts_level = 'INFO'
```

**celery.py**
```
from multiprocessing.pool import ThreadPool
from loguru import logger
from celery import shared_task
from celery import Celery

import logging
from ..models import Log
from loguru import logger
from logger.service.unitofwork import log_repository
import asyncio
from asgiref.sync import sync_to_async
import nest_asyncio


class DatabaseLogHandler(logging.Handler):
    def emit(self, record):
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = logging._levelToName[record.levelno]
        if level is None:
            level = logging._levelToName[logging.NOTSET]

        entity = Log(caller=record.filename, level=level, message=record.msg, logger=record.name, thread_id=record.thread, process_id=record.process, process_name=record.processName)

        if record.extra.get('enqueue', False):
            future = sync_to_async(log_repository.insert)(entity)
            self.log_db(future)

        else:
            log_repository.insert(entity)

    def log_db(self, future):
        try:
            loop = asyncio.get_event_loop()
            nest_asyncio.apply(loop)
            return asyncio.run(loop.create_task(future))

        except RuntimeError:  # no event loop running:
            loop = asyncio.new_event_loop()
            return loop.run_until_complete(loop.create_task(future))
            
logger.configure(**{'handlers': [
        {
            'sink': DatabaseLogHandler(),
            'catch': True,
            'backtrace': True,
            'diagnose': True,
            'format': '{message}',
            'level': 'INFO',
            # 'enqueue':True
        }
    ]}


app = Celery('celery')
app.config_from_object('celeryconfig')
app.conf.beat_schedule = {
    'test': {
        'task': 'celery.test_func',
        'schedule': crontab(minute='*/2')
    }
}

def my_func(msg):
    logger_mp = logger.bind(enqueue=True)
    logger_mp.info(msg)
    logger_mp.complete()

@shared_task(bind=True)
def test_func(self):
    ThreadPool(2).map(my_func, [msg, msg, msg])
```

**commands**
```
celery -A celery beat -l INFO --uid=nobody --gid=nogroup --detach
celery -A celery worker -l INFO -E --uid=nobody --gid=nogroup -O fair --pool=gevent --hostname=celery-worker --autoscale=30,10
```


Excuse me if it's not 'minimal', but I think it can't be done, however **the error shouldn't be in loguru but in django which isn't greenlet safe with gevent**

**The real question of this issue let's say was how to create an async handler for the db**

**Comment by zN3utr4l** [comment]
Another question, is it correct to create a non async Handler like:
```
logger.configure(**{'handlers': [
        {
            'sink': DatabaseLogHandler(),
            'catch': True,
            'backtrace': True,
            'diagnose': True,
            'format': '{message}',
            'level': 'INFO',
            # 'enqueue':True
        }
    ]}
```
and then when needed async do
```
logger_mp = logger.bind(enqueue=True)
logger_mp.info(msg)
logger_mp.complete()
```

is it correct to use all this also with **multiprocessing.pool.ThreadPool**?

**Comment by Delgan** [comment]
To be honest, I don't fully understand the error you're facing. Is it really due to Loguru? I don't see it mentioned in the `Exception` traceback.

When `logger.info()` (for example) is called, there are two possibilities for the configured sink (assuming `enqueue=False`):
- it's called immediately with `sink(message)` if the `sink` is a synchronous function
- it's scheduled with `get_running_loop().create_task(sink(message))` if the `sink` is an asynchronous function

You need to adapt the sink to the Django function you want to use.

It seems that Gevent transforms worker threads into async functions, but on the other hand, the Django database complains that it doesn't want to be called from an async function. It's this incompatibility that you need to sort out, but unfortunately I'm not sure how to help you, and I don't think it's related to Loguru.
Maybe there exists another Django function that can be called from an async context? If so, you could call it from a async Loguru sink as in the simple example I gave.

Regarding your second question, note that using `logger.bind(enqueue=True)` won't change the handler type, it will just update the `extra` dict of each logged message.
Additionally, using `enqueue=True` is not compatible with Gevent by default, `monkey.patch_all(thread=False)` needs to be used.

**Comment by zN3utr4l** [comment]
Yes, the error is not related to loguru, the question has become: **_How to write a "Sink" for database that also supports async_**, but from what I understand from your last message, do` bind(enqueue=True)` doesn't change the "Sink" to execute `create_task(....)`, so should I declare from the beginning one handler with `enqueue `**True** and one with **False**? If they are then in an async function will both be called? Will it give error?

**Comment by Delgan** [comment]
@zN3utr4l Apologies for the confusion, re-reading the code you shared, I see you use `enqueue` from the `extra` dict to discriminate the behavior of your sink. In that case, using `logger.bind(enqueue=True)` is valid.
To clarify, it should not be confused with `logger.add(sink, enqueue=True)` which is not related to asynchronism. When `enqueue=True`, the messages are processed synchronously but in a background thread. That's the reason this argument does not interoperate well with Gevent if `threading` is patched.

The code you shared seems to behave as expected: by default the `log_repository.insert()` function is called, but if you create a new logger object with `new_logger = logger.bind(enqueue=True)` and use it to log a message, the `log_db()` function will be called instead.

>  should I declare from the beginning one handler with enqueue True and one with False? Will it give error?

I don't think you should do that, because the `enqueue` argument of handlers seems unrelated to your problem, as explained above.

> How to write a "Sink" for database that also supports async

Did you consider checking if there is a running event loop before deciding to use the asynchronous Django function? Something like this:

```python
class DatabaseLogHandler(logging.Handler):
    def emit(self, record):
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = logging._levelToName[record.levelno]
        if level is None:
            level = logging._levelToName[logging.NOTSET]

        entity = Log(caller=record.filename, level=level, message=record.msg, logger=record.name, thread_id=record.thread, process_id=record.process, process_name=record.processName)
        
        try:
            loop = asyncio.get_running_loop()
            future = sync_to_async(log_repository.insert)(entity)
            loop.create_task(future)
        except RuntimeError:
            log_repository.insert(entity)
```

Your implementation seems already close to that.

**Comment by zN3utr4l** [comment]
thanks for the replies, everything is clearer now.
