### ISSUE TITLE
Additional kwargs could cause `AttributeError`

### ISSUE THREAD

**Issue by ringsaturn** [Delgan/loguru#897]
Hi there,

Our team is using Loguru in our services, and we found a special use case could cause `AttributeError`.

Additional kwargs could cause `AttributeError`

```py
from loguru import logger

d = {}
try:
    d["x"]
except Exception as e:
    logger.exception(e, d=d)
```

Output:

```
Traceback (most recent call last):
  File "/my-project/l.py", line 5, in <module>
    d["x"]
KeyError: 'x'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/my-project/l.py", line 7, in <module>
    logger.exception(e, d=d)
  File "/my-project/venv/lib/python3.9/site-packages/loguru/_logger.py", line 1998, in exception
    __self._log("ERROR", None, False, options, __message, args, kwargs)
  File "/my-project/venv/lib/python3.9/site-packages/loguru/_logger.py", line 1954, in _log
    log_record["message"] = message.format(*args, **kwargs)
AttributeError: 'KeyError' object has no attribute 'format'
```

I suggest change this code:

https://github.com/Delgan/loguru/blob/d379fedd9b19401e937c63de0154caf9a11252ec/loguru/_logger.py#L2008-L2010

to:

```py
        elif (args or kwargs) and hasattr(message, "format"):
            colored_message = None
            log_record["message"] = message.format(*args, **kwargs)
```

Should fix this.

**Comment by Delgan** [comment]
Hi @ringsaturn. Thank you for offering to open a PR.

When `*args` or `**kwargs` are present, Loguru assumes they are intended for formatting. As per type hints, it's actually not allowed to pass `*args` or `**kwargs` when `message`  is anything but a `str`: https://github.com/Delgan/loguru/blob/d379fedd9b19401e937c63de0154caf9a11252ec/loguru/__init__.pyi#L401-L404

We could as you suggested add a check at run-time with `hasattr(message, "format")` or `isinstance(message, str)`. However, I think this solution is not optimal, as Loguru and Mypy would no longer be able to detect and report genuine user errors.

In fact, the problem goes deeper than that. It's basically a design flaw in Loguru. Historically, `*args` and `**kwargs` were used for formatting **only**. At some point, I decided to extend usage of `**kwargs` to also capture variables for structured logging (your case), while also retaining their formatting role. This was retrospectively a huge mistake, as it leads to different kind of unexpected errors like the one you faced. The two possibles usages of `**kwargs` (formatting and capturing) are incompatible, and there's no way to reconcile them without ambiguity.

I've been thinking about this lately, and I think the only viable solution for Loguru is to no longer use `**kwargs` for formatting. Positional arguments, on the other hand, can continue to exist as is and can be used for lazy formatting. With the popularity of f-string and structured logging, I suppose named-braces formatting is less useful today. It might be a bit confusing for the user to be able to use `{}` but not `{name}`, but I can't think of any other way to resolve these conflicts.

For now, I owuld simply suggest you to  `bind()` when your message is not a `str`:

```python
logger.bind(d=d).exception(e)
```

**Comment by ringsaturn** [comment]
Thank you for your comprehensive explanation since it's a design made years ago.

I have tried that solution and it works well.

Maybe we could add some warning level logs for those such use case after the final decision is made, like NumPy did for zero division *RuntimeWarning: divide by zero encountered in...* in the future.
