### ISSUE TITLE
subprocess logs are missing in sink file with joblib multiprocess

### ISSUE THREAD

**Issue by victor23d** [Delgan/loguru#908]
subprocess logs are missing in log file when using with joblib multiprocess

Reproduce:
Create 2 Python files, since joblib can not pickle function in the `__main__` module.

main.py:

```
import joblib
from loguru import logger
from file2 import *

def main():
    logger.add(sink='run.log')

    run_list = [1, 2, 3, 4]
    joblib.Parallel(n_jobs=4)(joblib.delayed(
        run)(n) for n in run_list)

if __name__ == '__main__':
    main()

```

file2.py:
```
from loguru import logger

def run(n):
    logger.info(f'in subprocess {n}')

```

Run main.py, you will see the console output work as expected, but run.log is empty, no log has been written.

Is this because the sink file can not support concurrent writing? or it's the pickle file issue from joblib? 

How to write these logs from the subprocess in the sink file?

related issue: https://github.com/Delgan/loguru/issues/498

**Comment by victor23d** [comment]
Looks like this is because when joblib creates new process, the singleton instance logger is recreated, so in the sub process logger is not the logger in the main process, so `logger.add(sink='run.log') ` is not available in subprocess logger.

However I tried pass logger as parameter, 
file2.py
```
def run(n, logger):
    logger.info(f'in subprocess {n}')
```
main.py
```
    joblib.Parallel(n_jobs=4)(joblib.delayed(
        run)(n, logger) for n in run_list)
```
I got this issue
```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\joblib\externals\cloudpickle\cloudpickle_fast.py", line 343, in _file_reduce
    raise pickle.PicklingError(
_pickle.PicklingError: Cannot pickle files that are not opened for reading: a
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Administrator\.pyenv\pyenv-win\versions\3.10.10\lib\site-packages\joblib\parallel.py", line 753, in _return_or_raise
    raise self._result
_pickle.PicklingError: Could not pickle the task to send it to the workers.

Process finished with exit code 1
```
If I remove line ` logger.add(sink='run.log')` , it will work without error, so logger is picklable, but if added sink file it becomes unpicklable.

**Comment by Delgan** [comment]
Hi @victor23d.

You're right, if the child process is created by "spawning" and not by "forking", then two different `logger` objects will be created, and they won't share the same handlers.

As you understood, the `logger` object must be passed from the parent process to the child process when it is created. However, there is a subtlety to this:
- the installed handlers must be "picklable" and this is not always the case (the error you encountered) ;
- even if the handlers were "picklable", the child process would only receive a copy of them. This means that both loggers will have the same configured handlers, but these handlers will process messages independently. This lack of synchronization can cause issues, for example if the handler in the parent and that in the child try to write to a file at the same time.

To overcome these problems, one should add handlers with the `enqueue=True` argument. This will ensure that handlers can be "picklable", and that access to handler resources is restricted to the main process.

More details are available in the documentation: [Compatibility with multiprocessing using enqueue argument](https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument).
