### ISSUE TITLE
Feature suggestion: Decorator for function

### ISSUE THREAD

**Issue by cgebbe** [Delgan/loguru#925]
Thanks a ton for this library. I build the following small decorator on top of it, maybe it's useful for others:

### utility

```python
@dataclass
class Trace:
    raise_exception: bool = True
    default_value_upon_exception: Any = None
    resolve_defaults: bool = True

    def __call__(self, func):
        @functools.wraps(func)
        def new_func(*args, **kwargs):
            dct = _resolve_args(
                func, *args, apply_defaults=self.resolve_defaults, **kwargs
            )
            logger.info(f"Starting {func.__name__} with {dct=}")
            try:
                res = func(*args, **kwargs)
            except Exception as err:
                logger.exception(err)
                if self.raise_exception:
                    raise
                else:
                    return self.default_value_upon_exception

            logger.success(f"Finishing  {func.__name__} with {dct=}")
            return res

        return new_func


def _resolve_args(func, *args, apply_defaults: bool = False, **kwargs):
    # from https://github.com/cgebbe/sandbox/blob/0a64c819b4fc9e4ade1176a3bfd84dd0810f8e8a/disk_cacher.py
    sig = inspect.signature(func)
    bounds = sig.bind(*args, **kwargs)
    if apply_defaults:
        bounds.apply_defaults()
    return bounds.arguments
```

### How to use

Given the following lines

```python
        @Trace(raise_exception=False, default_value_upon_exception="magic")
        def multiply(x: str, times=5) -> str:
            return x * (times / 0)

        print(multiply("foo"))
        print("This is printed too")
```

This prints

```
2023-07-19 15:53:42.654 | INFO     | __main__:new_func:86 - Starting multiply with dct={'x': 'foo', 'times': 5}
2023-07-19 15:53:42.654 | ERROR    | __main__:new_func:90 - division by zero
Traceback (most recent call last):

  File "/home/ubuntu/git/cgebbe_utils/cgebbe_utils/_loguru.py", line 110, in <module>
    print(multiply("foo"))
          └ <function multiply at 0x7fb3a3a4fbe0>

> File "/home/ubuntu/git/cgebbe_utils/cgebbe_utils/_loguru.py", line 88, in new_func
    res = func(*args, **kwargs)
          │     │       └ {}
          │     └ ('foo',)
          └ <function multiply at 0x7fb3a3a4fb50>

  File "/home/ubuntu/git/cgebbe_utils/cgebbe_utils/_loguru.py", line 108, in multiply
    return x * (times / 0)
           │    └ 5
           └ 'foo'

ZeroDivisionError: division by zero
magic
We still continue though...
```

**Comment by Delgan** [comment]
Hi!

Thanks for sharing the decorator you created. I don't plan to integrate it into Loguru, though, because in my opinion it's a feature outside the scope of this library. There are many possible decorators, such as elapsed time measurement for example. Therefore, it's preferable to let users build such utilities on top of the library. In this way, Loguru just provides a framework for logging, but doesn't do the logging itself (apart from `@logger.catch()`).

However I'm sure it may be useful to some other people. :+1:

**Comment by jamazi** [comment]
Check this:
https://github.com/jamazi/dcclog/blob/master/src/dcclog/wrapper.py
