### ISSUE TITLE
Logging error in loguru handler when using `__InterceptHandler` and `django-ninja`

### ISSUE THREAD

**Issue by AlTosterino** [Delgan/loguru#937]
Hey!

Currently, I'm using `django-ninja` as my web framework, and I've added loguru as my main logger.
I've also used `InterceptHandler` class from documentation to make sure all logs goes through loguru.

My setup right now looks like this:

```python

DEFAULT_FORMAT = (
    "| <green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | "
    "<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    " | {extra}"
)


class __InterceptHandler(logging.Handler): 
    def emit(self, record: logging.LogRecord) -> None:
        # Get corresponding Loguru level if it exists.
        level: Union[int, str]
        try:
            level = logger.level(record.levelname).name
        except ValueError:
            level = record.levelno

        frame: Optional[FrameType]
        frame, depth = sys._getframe(6), 6
        while frame and frame.f_code.co_filename == logging.__file__:
            frame = frame.f_back
            depth += 1
        logger.opt(depth=depth, exception=record.exc_info).log(level, record.getMessage())
        
def configure_logging(
    level: Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] = "DEBUG",
    serialize: bool = False,
    backtrace: bool = True,
    colorize: bool = True,
    diagnose: bool = True,
) -> None:
    logger.remove()
    logging.basicConfig(handlers=[__InterceptHandler()], level="WARNING", force=True)
    
    logger.add(
        sys.stdout,
        format=format,
        level=level,
        serialize=serialize,
        backtrace=backtrace,
        colorize=colorize,
        diagnose=diagnose,
        enqueue=True,
    )
```

Everything works great unless there's `ValidationError` raised from `django-ninja` (which essential is exception from Pydantic itself I guess), which looks like this using default Python `logging` module:
```shell
> File "/Users/Tosuto/.../.venv/lib/python3.11/site-packages/ninja/operation.py", line 264, in run
    values = self._get_values(request, kw, temporal_response)
             │    │           │        │   └ <HttpResponse status_code=200, "application/json; charset=utf-8">
             │    │           │        └ {'key': 'value'}
             │    │           └ <ASGIRequest: GET '/api/internal/...'>
             │    └ <function Operation._get_values at 0x107bcb060>
             └ <ninja.operation.AsyncOperation object at 0x1091213d0>
  File "/Users/Tosuto/.../.venv/lib/python3.11/site-packages/ninja/operation.py", line 229, in _get_values
    raise ValidationError(errors)
          │               └ [{'loc': ('query', 'key'), 'msg': 'field required', 'type': 'value_error.missing'}]
          └ <class 'ninja.errors.ValidationError'>

ninja.errors.ValidationError
```

But using loguru I'm getting `Logging error in loguru handler`:
```shell
--- Logging error in Loguru Handler #4 ---
Record was: None
Traceback (most recent call last):
  File "/Users/Tosuto/.../.venv/lib/python3.11/site-packages/loguru/_handler.py", line 291, in _queued_writer
    message = queue.get()
              ^^^^^^^^^^^
  File "/Users/Tosuto/.pyenv/versions/3.11.4/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ValidationError.__init__() missing 1 required positional argument: 'errors'
--- End of logging error ---
```

I know that this error is causes by `enqueue=True` and I enabled it as I'm working constantly in async context.
Is there any way to fix this issue only for specific loggers, e.g. `django-ninja`? Or any workaround for that?

Thanks in advance, and thanks for this awesome package 🚀

**Comment by Delgan** [comment]
Hi @AlTosterino.

This problems occurs because `ValidationError` is pickable but not un-picklable. This is an oversight quite frequent when library authors create custom `Exception`. However, technically nothing prevents the `ValidationError` to be properly un-pickled. For this reason, I reported the issue to the `django-ninja` project: https://github.com/vitalik/django-ninja/issues/822

I could catch this kind of error during de-serialization of logged message by using a generic `try / except` (and I think I plan to do so), but it's always better if this can be fixed upstream, as otherwise you'll lose part of the `Exception` information.

**Comment by AlTosterino** [comment]
Thanks for very nice explanation and for passing this issue to `django-ninja`!
