### ISSUE TITLE
What is the best practice to use the logger for every file ?

### ISSUE THREAD

**Issue by leviethung2103** [Delgan/loguru#956]
Hello, 

I am wondering how to use the logger for every file ?

For example,
I have  2 files: `main.py`, `utils.py`.

Currently, I've imported loguru for each file. Can we use one loguru for all the files the project ? Thank you

**Comment by AlTosterino** [comment]
Hey,

Importing `from loguru import logger` in every file is the way that you should use `loguru`.

From documentation:

[The main concept of Loguru is that there is one and only one logger](https://loguru.readthedocs.io/en/stable/overview.html#ready-to-use-out-of-the-box-without-boilerplate)

[Apart from that, usage is globally the same, once the logger object is created or imported you can start using it to log messages with the appropriate severity (logger.debug("Dev message"), logger.warning("Danger!"), etc.), messages which are then sent to the configured handlers.](https://loguru.readthedocs.io/en/stable/resources/migration.html#fundamental-differences-between-logging-and-loguru)

So answer to `Currently, I've imported loguru for each file. Can we use one loguru for all the files the project ?` is -- Yes

**Comment by Delgan** [comment]
As explained by @AlTosterino, you're actually expected to use `from loguru import logger` in every file for logging. However, you should configure the `logger` (i.e. adding handlers) only once (probably in `main.py`). The `logger` object is a unique instance, therefore the setup will be shared among all files importing it.

**Comment by chenlujjj** [comment]
hi @Delgan I got a problem when I used loguru with customized formatter and patch, maybe it's related with the global logger idea.

How to reproduce:
demo_log.py
```
import sys
from loguru import logger
import json


def serialize(record):
    subset = {
        "time": str(record["time"]),
        "timestamp": record["time"].timestamp(),
        "source": record["file"].name,
        "line": record["line"],
        "message": record["message"],
        "level": record["level"].name,
    }
    # if record["exception"]:
    #     subset["exception"] = record["exception"]
        # subset["exception"]["exc_info"] = record["text"]
    return json.dumps(subset)


def patching(record):
    record["extra"]["serialized"] = serialize(record)


multiline = """this is
a multiline
logs
"""

logger.remove()
logger = logger.patch(patching)
logger.add(sys.stderr, format="{extra[serialized]}")
# logger.add(sys.stderr, serialize=True)
logger.info(multiline)
logger.warning("aaa")

try:
    1 / 0
except ZeroDivisionError:
    logger.exception("What?!")

from demo_log_2 import fn

fn()

```

demo_log_2.py
```
print("before import logger")
from loguru import logger
print("after import logger")

def fn():
    logger.info("inside fn")

logger.info("inside demo log 2")

```

When I ran `python3 demo_log.py`, the output is:

```
{"time": "2024-01-11 23:10:53.956991+08:00", "timestamp": 1704985853.956991, "source": "demo_log.py", "line": 34, "message": "this is\na multiline\nlogs\n", "level": "INFO"}
{"time": "2024-01-11 23:10:53.957118+08:00", "timestamp": 1704985853.957118, "source": "demo_log.py", "line": 35, "message": "aaa", "level": "WARNING"}
{"time": "2024-01-11 23:10:53.957176+08:00", "timestamp": 1704985853.957176, "source": "demo_log.py", "line": 40, "message": "What?!", "level": "ERROR"}
Traceback (most recent call last):

> File "/Users/clx/Codes/xxx/demo_log.py", line 38, in <module>
    1 / 0

ZeroDivisionError: division by zero
before import logger
after import logger
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(microseconds=18491), 'exception': None, 'extra': {}, 'file': (name='demo_log_2.py', path='/Users/clx/Codes/xxx/demo_log_2.py'), 'function': '<module>', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 8, 'message': 'inside demo log 2', 'module': 'demo_log_2', 'name': 'demo_log_2', 'process': (id=11357, name='MainProcess'), 'thread': (id=140704285939456, name='MainThread'), 'time': datetime(2024, 1, 11, 23, 10, 53, 961759, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'CST'))}
Traceback (most recent call last):
  File "/Users/clx/Codes/xxx/.venv/lib/python3.11/site-packages/loguru/_handler.py", line 175, in emit
    formatted = precomputed_format.format_map(formatter_record)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'serialized'
--- End of logging error ---
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(microseconds=20330), 'exception': None, 'extra': {}, 'file': (name='demo_log_2.py', path='/Users/clx/Codes/xxx/demo_log_2.py'), 'function': 'fn', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 6, 'message': 'inside fn', 'module': 'demo_log_2', 'name': 'demo_log_2', 'process': (id=11357, name='MainProcess'), 'thread': (id=140704285939456, name='MainThread'), 'time': datetime(2024, 1, 11, 23, 10, 53, 963598, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'CST'))}
Traceback (most recent call last):
  File "/Users/clx/Codes/xxx/.venv/lib/python3.11/site-packages/loguru/_handler.py", line 175, in emit
    formatted = precomputed_format.format_map(formatter_record)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'serialized'
--- End of logging error ---
```

Seems like the logger in demo_log_2.py is not the one in demo_log.py

**Comment by Delgan** [comment]
@chenlujjj Your `serialize()` function will only called for logs emitted by the patched `logger` object. The `logger` in `demo_log_2.py` isn't patched, therefore the `record` emitted won't contain the `serialized` attribute, and the formatter will fail.

In your case, since all logs emitted by your application must be serialized, I suggest to use the `patcher` parameter of [`logger.configure()`](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) instead of `logger.patch()`. In this way, your function will be installed "globally".

**Comment by chenlujjj** [comment]
Thank you, @Delgan , `logger.configure(patcher=patching)` works for me
