### ISSUE TITLE
 How to record different information to different log files in one class the `main.py` ref，when configure the logger (i.e. adding handlers) only once in main.py. 

### ISSUE THREAD

**Issue by keymou** [Delgan/loguru#973]
**Description**:
I am currently using the Loguru logging library in my project. However, I encountered a problem, that is, the `main.py` needs to define `logger`  for recording task brief information. The custom `router.py`  reference `logger` records some brief information , but at the same time, in this `router.py` , it will pass logger to record some device details to a different log file. 

**Expected Behavior**:
brief.log record information（brief.log records device connection success, failure or reconnection information）:

2023-09-04 16:29:43.698 | INFO | c1 连接成功！
2023-09-04 16:29:43.720 | INFO | c1 连接成功！

c1.log record information:

c1 device version information
……

c2.log record information:

c2 device version information
……

**Actual Behavior**:
`brief.log` does not record any information

Snippet - main.py

```python
import sys
from loguru import logger
from router import Device
from concurrent.futures import ThreadPoolExecutor


def connect_device(device: dict, name):
    ssh_conn = Device(device=device, name=name)
    output = ssh_conn.show_version()


if __name__ == '__main__':
    print("Starting……")

    c1= {
        "device_type": "huawei_telnet",
        "host": "192.4.0.222",
        "username": "user1",
        "password": "sdfwrf!"

    }

    c2= {
        "device_type": "huawei_telnet",
        "host": "192.4.1.222",
        "username": "user1",
        "password": "sdfwrf"
    }
    names = ["c1", "c2"]
    all_devices = [c1, c2]
    logger.remove()
    logger.add(
        'breif.log',
        format='{time:YYYY-MM-DD HH:mm:ss.SSS} | {level} | \n{message}\n',
        filter=lambda record: record["extra"]["task"] == "A",
        enqueue=True,
        rotation='10 MB',
    )

    with ThreadPoolExecutor(max_workers=len(all_devices)) as executor:
        executor.map(connect_device, all_devices, names)

    print("End……")
```

Snippet - router.py
```python
from copy import deepcopy
from functools import wraps
from typing import Optional
from time import sleep
from loguru import logger
from netmiko import BaseConnection, ConnectHandler, NetmikoAuthenticationException, NetmikoTimeoutException


class Device(object):

    def __init__(self, device: dict, name, max_tries: int = 30, delay: int = 10, size: int = 50) -> None:
        self._device = device
        self._name = name
        self._max_tries = max_tries
        self._delay = delay
        self._size = size
        self.client: Optional[BaseConnection] = None
        self._device.update(
            {
                "session_log": f"{self._name}.log",
                "session_log_record_writes": True,
                "session_log_file_mode": 'append',
                "keepalive": 5,
                "timeout": 300,
                "encoding": "utf-8",
            }
        )
        self._session_log = f'{self._name}.log'
        logger.remove()
        self.logger_ = deepcopy(logger)
        self.logger_.add(
            self._session_log,
            format='{time:YYYY-MM-DD HH:mm:ss.SSS} | {message}',
            level="INFO",
            enqueue=True,
            rotation=f'{self._size}MB',
            compression='zip'
        )
        self._connect()

    @property
    def _device_name(self):
        return self._name

    def log_and_sleep(self, msg, tries):
        logger.info(f'{msg} 重试次数: {tries}')
        sleep(self._delay)

    def _connect(self):
        self.client = ConnectHandler(**self._device)
        logger.bind(task='A')
        logger.info(f'{self._device_name} 连接成功！')
        return self.client

    def _reconnect(self):
        self.client = ConnectHandler(**self._device)
        logger.bind(task='A')
        logger.info(f'{self._device_name} 重连成功！')
        return self.client

    def disconnect(self):
        self.client.disconnect()
        logger.bind(task='A')
        logger.info(f'{self._device_name} 断开连接成功!')

    def log2file(self, recv: str):
        if recv:
            for line in recv.split("\n"):
                self.logger_.info(line)

    def show_version(self):
        output = self.client.send_command(
            command_string='show version',
        )
        self.log2file(output)

```

The problem should be caused by `logger.remove()` when creating the `Device` cls, but I don’t know how to record different information to different log files in one class. I hope I can get guidance and help.

**Comment by Delgan** [comment]
You probably need some kind of filtering. Take a look at this documentation page: [Creating independent loggers with separate set of handlers](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers).

**Comment by keymou** [comment]
> You probably need some kind of filtering. Take a look at this documentation page: [Creating independent loggers with separate set of handlers](https://loguru.readthedocs.io/en/stable/resources/recipes.html#creating-independent-loggers-with-separate-set-of-handlers).

After modifying according to the example creating independent loggers with separate set of handlers,,a KeyError exception occurs during operation.

Snippet - main.py
```python
import sys
from loguru import logger
from router import Device
from concurrent.futures import ThreadPoolExecutor


def connect_device(device: dict, name):
    ssh_conn = Device(device=device, name=name)
    output = ssh_conn.show_version()


if __name__ == '__main__':
    print("Starting……")

    c1= {
        "device_type": "huawei_telnet",
        "host": "192.4.0.222",
        "username": "user1",
        "password": "sdfwrf!"

    }

    c2= {
        "device_type": "huawei_telnet",
        "host": "55.18.33.29",
        "username": "user1",
        "password": "sdfwrf"
    }
    names = ["c1", "c2"]
    all_devices = [c1, c2]
    logger.remove()
    logger.add(
        'breif.log',
        format='{time:YYYY-MM-DD HH:mm:ss.SSS} | {level} | \n{message}\n',
        filter=lambda record: record["extra"]["task"] == "A",
        enqueue=True,
        rotation='10 MB',
    )

    with ThreadPoolExecutor(max_workers=len(all_devices)) as executor:
        executor.map(connect_device, all_devices, names)

    print("End……")
```
Snippet - router.py
```python
class Device(object):

    def __init__(self, device: dict, name, debug_mode: bool = True, debug_level: str = 'DEBUG', debug_size: int = 50,
                 max_tries: int = 30, delay: int = 10, size: int = 50, **kwargs) -> None:
        self._device = device
        self._name = name
        self._max_tries = max_tries
        self._delay = delay
        self._size = size
        self.client: Optional[BaseConnection] = None
        self._device.update(
            {
                "session_log": f"{self._name}.log",
                "session_log_record_writes": True,
                "session_log_file_mode": 'append',
                "keepalive": 5,
                "timeout": 300,
                # 设置设备的编码格式为UTF-8
                "encoding": "utf-8",
            }
        )
        self._session_log = f'{self._name}_{device.get("host")}.log'
        logger.add(
            self._session_log,
            filter=lambda record: record["extra"]["device_name"] == f"{self._name}",
            format='{time:YYYY-MM-DD HH:mm:ss.SSS} | {message}',
            enqueue=True,
            rotation=f'{self._size} MB',
        )
        self._connect()

    @property
    def _device_name(self):
        return self._name

    def log_and_sleep(self, msg, tries):
        logger.bind(task='A')
        logger.info(f'{msg} 重试次数: {tries}')
        sleep(self._delay)

    @handle_exceptions
    def _connect(self):
        self.client = ConnectHandler(**self._device)
        logger.bind(task='A')
        logger.info(f'{self._device_name} 连接成功！')
        return self.client

    @handle_exceptions
    def _reconnect(self):
        self.client = ConnectHandler(**self._device)
        logger.bind(task='A')
        logger.info(f'{self._device_name} 重连成功！')
        return self.client

    @handle_exceptions
    def disconnect(self):
        self.client.disconnect()
        logger.bind(task='A')
        logger.info(f'{self._device_name} 断开连接成功!')

    def log2file(self, recv: str):
        if recv:
            for line in recv.split("\n"):
                logger.bind(device_name=self._name)
                logger.info(line)

    def show_version(self):
        output = self.client.send_command(
            command_string='show version',
        )
        self.log2file(output)
```
Exception occurs when running
```
D:\ProgramData\Miniconda3\envs\PyQt-Fluent-Widgets-PyQt5\python.exe D:\project\logger.py 
Starting……
--- Logging error in Loguru Handler #1 ---
Record was: {'elapsed': datetime.timedelta(seconds=1, microseconds=981000), 'exception': None, 'extra': {}, 'file': (name='router_.py', path='D:\\project\\router_.py'), 'function': '_connect', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 98, 'message': 'c2连接成功！', 'module': 'router_', 'name': 'router_', 'process': (id=14928, name='MainProcess'), 'thread': (id=14360, name='ThreadPoolExecutor-0_1'), 'time': datetime(2023, 9, 4, 17, 8, 40, 537236, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '马来西亚半岛标准时间'))}
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\PyQt-Fluent-Widgets-PyQt5\lib\site-packages\loguru\_handler.py", line 124, in emit
    if not self._filter(record):
  File "D:\project\logger.py", line 50, in <lambda>
    filter=lambda record: record["extra"]["task"] == "A",
KeyError: 'task'
--- End of logging error ---
--- Logging error in Loguru Handler #3 ---
Record was: {'elapsed': datetime.timedelta(seconds=1, microseconds=981000), 'exception': None, 'extra': {}, 'file': (name='router_.py', path='D:\\project\\router_.py'), 'function': '_connect', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 98, 'message': 'c2 连接成功！', 'module': 'router_', 'name': 'router_', 'process': (id=14928, name='MainProcess'), 'thread': (id=14360, name='ThreadPoolExecutor-0_1'), 'time': datetime(2023, 9, 4, 17, 8, 40, 537236, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), '马来西亚半岛标准时间'))}
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\PyQt-Fluent-Widgets-PyQt5\lib\site-packages\loguru\_handler.py", line 124, in emit
    if not self._filter(record):
  File "D:\project\router_.py", line 68, in <lambda>
    filter=lambda record: record["extra"]["device_name"] == f"{self._name}",
KeyError: 'device_name'
--- End of logging error ---
```

**Comment by Delgan** [comment]
Not all your logs contain the `"device_name"`, only those created by the `logger` returned by the `bind(device_name=self._name)` method will.

You can use `filter=lambda record: record["extra"].get("device_name")` to avoid the `KeyError`, as it will return `None` if the key does not exist.

**Comment by Delgan** [comment]
I see that you call `logger.bind(task='A')` but do not assign the result to any variable. This is likely a mistake, because `logger.bind()` does not modify the `logger` in place but return a new bound `logger`, instead. That means you probably need to do something like `self._logger = logger.bind(task='A')` and use `self._logger` in your methods.

**Comment by keymou** [comment]
> I see that you call `logger.bind(task='A')` but do not assign the result to any variable. This is likely a mistake, because `logger.bind()` does not modify the `logger` in place but return a new bound `logger`, instead. That means you probably need to do something like `self._logger = logger.bind(task='A')` and use `self._logger` in your methods.

You are right, the log can be recorded normally after correction, thank you very much for your patience。
