### ISSUE TITLE
Example of Custom Log Levels doesn't seem to work

### ISSUE THREAD

**Issue by avalon60** [Delgan/loguru#992]
Hi.

I am using loguru v0.7.2.

I have tried to create a custom log level, based on the example in the guide found [here](https://betterstack.com/community/guides/logging/loguru/).

My code looks like this:

```
from loguru import logger as logr

class LogGen:
    @staticmethod
    def logger_gen(logger_name: str = 'BDD Test', log_file: str = 'bdd_testing.log') -> loguru.logger:
        """Instantiate a logger.
        :param logger_name: Default logger name is "BDD Test"
        :param log_file: Default log filename is bdd_testing.log
        :return: logging.Logger
        """

        log_level_code = ohai.config_property(config_section='logger', config_property='log_level', default="INFO")
        log_stamping = ohai.config_property(config_section='logger', config_property='log_stamping', default="n")
        inc_stderr = ohai.config_property(config_section='logger', config_property='inc_stderr', default="y")

        logr.level("FATAL", no=60, color="<red>", icon="!!!")
        logr.log("FATAL", "A user updated some information.")

        if inc_stderr.lower() != 'y':
            logr.remove(0)

        if log_stamping.lower() == 'y':
            logr.add(sink=Path(f"{ohai.LOGS_DIR}/{log_file}"), level=log_level_code,
                     format="{extra} | {time} | {level} | {message}")
            log = logr.bind(ls=LOG_STAMP)
        else:
            log = logr
        global logger
        logger = log
        return log
```
However I get the exception:

```
      Traceback (most recent call last):
        File "C:\Development\PycharmProjects\foreg_test\venv\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "C:\Development\PycharmProjects\foreg_test\venv\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\foreg_login.py", line 16, in launch_browser
          context.logger = LogGen().logger_gen()
        File "C:\Development\PycharmProjects\foreg_test\lib\loggerutl.py", line 55, in logger_gen
          logr.level("FATAL", no=61, color="<red>", icon="!!!")
        File "C:\Development\PycharmProjects\foreg_test\venv\lib\site-packages\loguru\_logger.py", line 1588, in level
          raise TypeError("Level '%s' already exists, you can't update its severity no" % name)
      TypeError: Level 'FATAL' already exists, you can't update its severity no
```

**Comment by Delgan** [comment]
Hi.

Are you sure you're not inadvertently calling `logger_gen()` multiple times? If `logger.level(...)` in your code is called twice, it will raise the error you faced.

```python
from loguru import logger

logger.level("FATAL", no=60, color="<red>", icon="!!!")  # OK
logger.level("FATAL", no=60, color="<red>", icon="!!!")  # TypeError
```

**Comment by avalon60** [comment]
> Hi.
> 
> Are you sure you're not inadvertently calling `logger_gen()` multiple times? If `logger.level(...)` in your code is called twice, it will raise the error you faced.
> 
> ```python
> from loguru import logger
> 
> logger.level("FATAL", no=60, color="<red>", icon="!!!")  # OK
> logger.level("FATAL", no=60, color="<red>", icon="!!!")  # TypeError
> ```

Hi @Delgan. I think that was the case. The implementation is for use in a behave/selenium test framework. The repeated common calls across scenarios were probably causing the issue. The class, is implemented as a package. Moving the `logger.level()` statements outside of the class, did the trick. 

Thanks for your help.

**Comment by Delgan** [comment]
Great, I'm closing this issue then. :+1:
